<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>close button</name>
   <tag></tag>
   <elementGuidId>96030683-08b0-444a-a077-cca44e54ff20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;radix-:r31:&quot;]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Close&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c7c7745d-af20-407a-9470-f3ae208e4e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ri-close-line tw-text-center tw-text-[30px] tw-leading-none tw-text-[#1A428A]</value>
      <webElementGuid>2e57800b-6976-4f86-9718-4bab6569fc93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r15:&quot;)/button[@class=&quot;focus:tw-ring-ring data-[state=open]:tw-bg-accent data-[state=open]:tw-text-muted-foreground tw-absolute tw-end-4 tw-top-4 tw-z-10 tw-m-auto tw-flex tw-h-[35px] tw-h-[45px] tw-w-[35px] tw-w-[45px] tw-cursor-pointer tw-items-center tw-justify-center tw-rounded-full tw-bg-white tw-leading-none tw-shadow tw-transition tw-duration-150 tw-ease-in-out hover:tw-bg-[#efefef] focus:tw-outline-none focus:tw-ring-2 focus:tw-ring-offset-2 disabled:tw-pointer-events-none&quot;]/i[@class=&quot;ri-close-line tw-text-center tw-text-[30px] tw-leading-none tw-text-[#1A428A]&quot;]</value>
      <webElementGuid>b41e0942-2ad6-4de9-9a34-3b5322f7b6a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r15:']/button/i</value>
      <webElementGuid>eae825ba-bbbb-4c34-84f7-43484f60ed0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/i</value>
      <webElementGuid>7bb92a01-85d7-4e28-960e-79159f83663c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
