<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_</name>
   <tag></tag>
   <elementGuidId>cdb59a14-db34-4ee6-86b6-9301a38a4bca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.bold.tw-text-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:r15:']/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;يرجى إدخال رقم هاتفك للتأكد من أنك لن تفوت أي من المواد التعليمية!&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>124cecf8-9d54-417f-a35e-92572cf06c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>mobile</value>
      <webElementGuid>fa7d5601-4143-4378-9776-5c8a1d8a5067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bold tw-text-sm</value>
      <webElementGuid>eb66514a-547d-4082-abeb-8716a8421c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>يرجى إدخال رقم هاتفك للتأكد من أنك لن تفوت أي من المواد التعليمية!</value>
      <webElementGuid>006f73c7-4dcd-4db5-84d9-58647b7692d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r15:&quot;)/div[@class=&quot;tw-flex tw-flex-col tw-gap-4 tw-pt-12&quot;]/label[@class=&quot;bold tw-text-sm&quot;]</value>
      <webElementGuid>875d24c2-8df4-4c79-ab3f-9b98f5061019</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r15:']/div/label</value>
      <webElementGuid>ff6be528-6d15-4c4f-8823-6148c876aadf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='صفحاتنا على مواقع التواصل الاجتماعي'])[1]/following::label[1]</value>
      <webElementGuid>9fbb290a-17e0-45a8-91a1-f8033762ef46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WINDOWS'])[1]/following::label[1]</value>
      <webElementGuid>2fe5c13b-ec4c-4c2b-af8f-8ed0d7e1cd32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تحميل الملف'])[15]/preceding::label[1]</value>
      <webElementGuid>32b40bb8-0a2b-458d-900f-8b674286310b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::label[1]</value>
      <webElementGuid>fcd68285-2a75-4f5f-b41d-36d56c898b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='يرجى إدخال رقم هاتفك للتأكد من أنك لن تفوت أي من المواد التعليمية!']/parent::*</value>
      <webElementGuid>c0fca08f-64a2-45a2-acf8-10c82330db45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>8882b084-bceb-4df8-96d7-09ba18974eb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'يرجى إدخال رقم هاتفك للتأكد من أنك لن تفوت أي من المواد التعليمية!' or . = 'يرجى إدخال رقم هاتفك للتأكد من أنك لن تفوت أي من المواد التعليمية!')]</value>
      <webElementGuid>2d5f8f8c-8044-44b4-ae9a-47ac5796d138</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
