<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button exma material</name>
   <tag></tag>
   <elementGuidId>b311285d-ce94-48f1-b660-28c66e952a3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;radix-:rj:-trigger-quizzes&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;اختبارات المادة&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>862d9b75-788c-4e96-97eb-a57a936d7aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center justify-center whitespace-nowrap rounded-sm px-3 py-1.5 text-sm font-medium ring-offset-background transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 data-[state=active]:bg-background data-[state=active]:text-foreground data-[state=active]:shadow-sm tw-h-[40px] max-md:!tw-text-[14px] max-md:tw-px-2 tw-whitespace-nowrap md:!tw-mt-8 max-md:tw-relative max-md:!tw-w-full max-md:tw-border-b-4 max-md:tw-rounded-none data-[state=active]:after:tw-absolute data-[state=active]:after:-tw-bottom-[11px] md:tw-bg-[#3D5A67] max-md:tw-border-[#ADC5CE] !tw-drop-shadow-xl tw-text-lg tw-p-1 tw-px-6 tw-rounded-[14px] medium lg:tw-font-bold tw-text-[#ffffff] tw-flex tw-items-center tw-justify-center</value>
      <webElementGuid>3bc2eae4-ac4b-4613-a597-02afe1ab490b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0fb6056f-6337-44f9-8749-ff1dc0e968f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>a607da04-c11b-4b31-910c-6b0af83240b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>588358c0-df50-457e-b499-a2f3c5b90c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:R1qjml6:-content-quizzes</value>
      <webElementGuid>de2fd8f8-6a5f-4058-992c-2b516f8c1afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>inactive</value>
      <webElementGuid>c103fe5d-99e3-4d56-96f7-2c1c0c29ed7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-:R1qjml6:-trigger-quizzes</value>
      <webElementGuid>0e28cf05-cfb9-4e30-ae91-52a6352eb48c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>62442c55-fd0e-4c65-95b8-09ab9824ad02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orientation</name>
      <type>Main</type>
      <value>horizontal</value>
      <webElementGuid>88ae5969-8337-4747-864d-5752e43273dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/e-school/%D8%A7%D9%84%D8%B3%D8%A7%D8%A8%D8%B9-%D9%81%D8%B5%D9%84-%D8%A3%D9%88%D9%84-%D8%A7%D9%84%D8%B9%D9%84%D9%88%D9%85/quizzes?grade=7</value>
      <webElementGuid>64af142c-f61e-4b83-b7e4-3af77167258c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>اختبارات المادة</value>
      <webElementGuid>590cada6-d43b-4e19-917d-25e9a82e7389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:R1qjml6:-trigger-quizzes&quot;)</value>
      <webElementGuid>5913cc30-4b35-402c-b696-b81fd667f96d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='radix-:R1qjml6:-trigger-quizzes']</value>
      <webElementGuid>a5cd8531-1010-4bf1-83ab-2e13c7a406e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/div/div/div[3]/div/a[3]</value>
      <webElementGuid>c9034594-c585-452c-81bd-fdade66c546c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'اختبارات المادة')]</value>
      <webElementGuid>a71e052d-628d-4be1-a0f7-0e51b3375747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ملفات المادة'])[1]/following::a[1]</value>
      <webElementGuid>153e2d3d-42e3-42b8-817a-0e12836bdea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='فهرس الكتاب'])[1]/following::a[2]</value>
      <webElementGuid>17734175-20cd-433a-a818-1d706539bcc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='دروس مجانية'])[1]/preceding::a[1]</value>
      <webElementGuid>145309e8-8bde-4ca5-aacd-e72bcac0342d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الأرض'])[1]/preceding::a[2]</value>
      <webElementGuid>ec99be68-75a2-487c-bb01-c075a789d510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='اختبارات المادة']/parent::*</value>
      <webElementGuid>1df0afd8-48c8-418a-ac13-c04bf682f6a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/e-school/%D8%A7%D9%84%D8%B3%D8%A7%D8%A8%D8%B9-%D9%81%D8%B5%D9%84-%D8%A3%D9%88%D9%84-%D8%A7%D9%84%D8%B9%D9%84%D9%88%D9%85/quizzes?grade=7')]</value>
      <webElementGuid>acd140d6-5ef2-49b7-8588-8a55a67e882f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a[3]</value>
      <webElementGuid>2a00ade9-9757-4cc1-b1bd-cdfe4ec0c1ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@type = 'button' and @id = 'radix-:R1qjml6:-trigger-quizzes' and @href = '/e-school/%D8%A7%D9%84%D8%B3%D8%A7%D8%A8%D8%B9-%D9%81%D8%B5%D9%84-%D8%A3%D9%88%D9%84-%D8%A7%D9%84%D8%B9%D9%84%D9%88%D9%85/quizzes?grade=7' and (text() = 'اختبارات المادة' or . = 'اختبارات المادة')]</value>
      <webElementGuid>88d6b090-f4c8-4e47-a0c8-8f53f095958d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
