<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button school</name>
   <tag></tag>
   <elementGuidId>4a7030a6-19fe-44c1-9cb3-cb52ee03b2da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;__next&quot;]/div[1]/div[2]/div[2]/div[2]/div/div/div[2]/nav/ol/li[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;المدرسة&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0f39d215-7364-4dd6-99d6-99916a942a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-transition-colors hover:tw-text-slate-950 dark:hover:tw-text-slate-50 bold !tw-text-base max-md:!tw-text-[14px] tw-text-white</value>
      <webElementGuid>42a56fe2-8230-42dc-bb08-51687d5fe2e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/e-school</value>
      <webElementGuid>abc29fc4-2a85-4e95-b5e5-d3e56b1ec328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>المدرسة</value>
      <webElementGuid>2bcfde94-7260-439b-812c-fbe19c80448b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;tw-flex tw-min-h-screen tw-w-full tw-flex-col tw-justify-between tw-bg-gradient-to-br tw-from-[#5F8998] tw-to-[#3D5A67]&quot;]/div[@class=&quot;tw-w-full&quot;]/div[@class=&quot;tw-relative tw-flex tw-w-full&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-relative !tw-w-full tw-px-4 md:tw-px-[30px] lg:tw-px-[40px] 2xl:tw-px-[100px] tw-w-full !tw-overflow-hidden&quot;]/div[1]/div[@class=&quot;tw-p-1 sm:tw-p-4&quot;]/div[@class=&quot;tw-my-5&quot;]/nav[@class=&quot;tw-px-5&quot;]/ol[@class=&quot;tw-flex tw-flex-wrap tw-items-center tw-gap-1.5 tw-break-words tw-text-sm tw-text-slate-500 sm:tw-gap-2.5 dark:tw-text-slate-400&quot;]/li[@class=&quot;tw-inline-flex tw-items-center tw-gap-1.5&quot;]/a[@class=&quot;tw-transition-colors hover:tw-text-slate-950 dark:hover:tw-text-slate-50 bold !tw-text-base max-md:!tw-text-[14px] tw-text-white&quot;]</value>
      <webElementGuid>de1f16e6-17fd-464f-92bd-3f0028a5e8eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/div/div/div[2]/nav/ol/li/a</value>
      <webElementGuid>7c4d3b24-6a15-4ce3-a9c1-a94799d1dc2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'المدرسة')]</value>
      <webElementGuid>abddd45f-b9af-4df0-8617-f69f0f4716d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الصف السابع | فصل أول'])[1]/following::a[1]</value>
      <webElementGuid>88d3119f-e226-46a0-a8c5-34f3f61b08a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='العلوم'])[1]/following::a[1]</value>
      <webElementGuid>8aa7f33b-8724-460b-9009-209bc493323e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='العلوم'])[2]/preceding::a[1]</value>
      <webElementGuid>7623adbd-d4b1-4c8d-a3da-859b7fb64738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='فهرس الكتاب'])[1]/preceding::a[2]</value>
      <webElementGuid>c509c16e-181e-4b3e-ac0d-c1123c4f3aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='المدرسة']/parent::*</value>
      <webElementGuid>c64b7ff9-8b04-4254-a3db-de05b2d6c10e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/e-school')])[2]</value>
      <webElementGuid>2eae638d-257c-44ba-9760-6271d6ccb526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>f161a1af-8e2b-4ee4-aed4-58d90965108f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/e-school' and (text() = 'المدرسة' or . = 'المدرسة')]</value>
      <webElementGuid>f0cfa44c-95f4-4840-a2b6-97f3e6f934dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
