<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button Book Index</name>
   <tag></tag>
   <elementGuidId>6e61773a-4bfe-46ef-9a22-b835698e9a14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='radix-:R1qjml6:-trigger-book-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;فهرس الكتاب&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d0ec1a0d-4fbf-4cc6-83e4-9ae95c4ce7eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center justify-center whitespace-nowrap rounded-sm px-3 py-1.5 text-sm font-medium ring-offset-background transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 data-[state=active]:bg-background data-[state=active]:text-foreground data-[state=active]:shadow-sm tw-h-[40px] max-md:!tw-text-[14px] max-md:tw-px-2 tw-whitespace-nowrap md:!tw-mt-8 max-md:tw-relative max-md:!tw-w-full max-md:tw-border-b-4 max-md:tw-rounded-none data-[state=active]:after:tw-absolute data-[state=active]:after:-tw-bottom-[11px] md:tw-bg-[#3D5A67] max-md:tw-border-[#ADC5CE] !tw-drop-shadow-xl tw-text-lg tw-p-1 tw-px-6 tw-rounded-[14px] medium lg:tw-font-bold tw-text-[#ffffff] md:!tw-bg-gradient-to-b md:!tw-from-[#F2A950] bold md:!tw-to-[#DF7017] !tw-bg-transparent max-md:!tw-border-b-[#4AA2D9] max-md:tw-border-t-[#1F70AA] tw-flex tw-items-center tw-justify-center</value>
      <webElementGuid>dc73ec78-6c27-4f68-a237-54f1fad46bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6f659d91-a6a4-42b4-8480-22c24014fe46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>4c854030-1782-49c9-8db5-501a003dda32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fd644bff-ba9e-4714-9388-013b3622aa35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:R1qjml6:-content-book-content</value>
      <webElementGuid>64d815a9-d493-4819-b27f-08a72119f11f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>04d9e5f2-1290-4de2-9619-aad05ab87c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-:R1qjml6:-trigger-book-content</value>
      <webElementGuid>dd00226d-3998-4087-82bc-0269420bb14c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>1d9b9674-30ef-4096-bd26-c279ae1c29ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orientation</name>
      <type>Main</type>
      <value>horizontal</value>
      <webElementGuid>076667f7-1928-4d91-bc48-14d9cfaf6edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/e-school/%D8%A7%D9%84%D8%B3%D8%A7%D8%A8%D8%B9-%D9%81%D8%B5%D9%84-%D8%A3%D9%88%D9%84-%D8%A7%D9%84%D8%B9%D9%84%D9%88%D9%85/book-content?grade=7</value>
      <webElementGuid>6ab4f437-c9e1-49a6-bd6c-9577c4de3797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>فهرس الكتاب</value>
      <webElementGuid>ce78db6e-50de-4429-ac24-086be0968579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:R1qjml6:-trigger-book-content&quot;)</value>
      <webElementGuid>d45459dc-fd1e-4da1-ba7e-b0072251cb81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='radix-:R1qjml6:-trigger-book-content']</value>
      <webElementGuid>707d8e49-7206-4c3d-90a3-8b6f3b6d94c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/div/div/div[3]/div/a</value>
      <webElementGuid>83eba9c5-4998-48a6-b7d1-e8fa2418b80f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'فهرس الكتاب')]</value>
      <webElementGuid>2c8dceec-69a5-4b97-8131-5901955cac7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='العلوم'])[2]/following::a[1]</value>
      <webElementGuid>44ec09c3-1906-40c4-943a-210b9fb5293d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='المدرسة'])[1]/following::a[2]</value>
      <webElementGuid>a7cc9d2d-690d-4f23-9dfc-c75d44c4f4b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ملفات المادة'])[1]/preceding::a[1]</value>
      <webElementGuid>1677034f-a4dd-416f-bcd4-e203b6823807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اختبارات المادة'])[1]/preceding::a[2]</value>
      <webElementGuid>fb68176f-e132-4be5-a706-73bb24c676f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='فهرس الكتاب']/parent::*</value>
      <webElementGuid>01dd1e66-ece1-4508-9469-d48cec85082c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/e-school/%D8%A7%D9%84%D8%B3%D8%A7%D8%A8%D8%B9-%D9%81%D8%B5%D9%84-%D8%A3%D9%88%D9%84-%D8%A7%D9%84%D8%B9%D9%84%D9%88%D9%85/book-content?grade=7')]</value>
      <webElementGuid>1abf433e-1911-4468-95b7-58513cad095b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div/a</value>
      <webElementGuid>270b572f-524f-474e-b264-8f20e9bb8939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@type = 'button' and @id = 'radix-:R1qjml6:-trigger-book-content' and @href = '/e-school/%D8%A7%D9%84%D8%B3%D8%A7%D8%A8%D8%B9-%D9%81%D8%B5%D9%84-%D8%A3%D9%88%D9%84-%D8%A7%D9%84%D8%B9%D9%84%D9%88%D9%85/book-content?grade=7' and (text() = 'فهرس الكتاب' or . = 'فهرس الكتاب')]</value>
      <webElementGuid>1cb19b92-c0b2-44a1-83af-5d0819f5e236</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
