<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>material 1</name>
   <tag></tag>
   <elementGuidId>ef21bca7-de07-4fcc-ba4e-0421c24942e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;radix-:r1g:-content-semester-one&quot;]/div/a[1]/div/div/div/p[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;اختبارات المادة&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4f9ebc9a-22f2-4818-90a1-4848d7b1c98d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center justify-center whitespace-nowrap rounded-sm px-3 py-1.5 text-sm font-medium ring-offset-background transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 data-[state=active]:bg-background data-[state=active]:text-foreground data-[state=active]:shadow-sm tw-h-[40px] max-md:!tw-text-[14px] max-md:tw-px-2 tw-whitespace-nowrap md:!tw-mt-8 max-md:tw-relative max-md:!tw-w-full max-md:tw-border-b-4 max-md:tw-rounded-none data-[state=active]:after:tw-absolute data-[state=active]:after:-tw-bottom-[11px] !tw-bg-[#6524BF] max-lg:!tw-w-full bold tw-text-white max-md:tw-border-none !tw-rounded-[14px] !tw-drop-shadow-xl tw-text-lg lg:tw-p-1 lg:tw-px-6 tw-flex tw-items-center tw-justify-center</value>
      <webElementGuid>39479ea2-d733-465b-87e7-aa5f8c540e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e05f019d-d5f7-493a-83a1-8e7e193bab8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>ef2a2f0a-d159-4ed7-a3a2-f858425bf97c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6f1c3f54-8217-4295-b0a0-067740244a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:r19:-content-quizzes</value>
      <webElementGuid>d60baf40-2d23-4e1e-8e54-00c1a8f91714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>inactive</value>
      <webElementGuid>b1baa184-613b-4025-81fd-7fee0deba03b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-:r19:-trigger-quizzes</value>
      <webElementGuid>f887a80d-02be-4842-933a-a7eff36bea7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c8019f2b-31d3-423c-be56-395ff928c1b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orientation</name>
      <type>Main</type>
      <value>horizontal</value>
      <webElementGuid>c18ad9a0-89dd-46bb-a368-89a3879e16b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/e-school/%D8%A7%D9%84%D8%A3%D9%88%D9%84-%D9%81%D8%B5%D9%84-%D8%A3%D9%88%D9%84-%D8%A7%D9%84%D8%B9%D9%84%D9%88%D9%85/quizzes?grade=1</value>
      <webElementGuid>d34c1244-a4b7-426c-afb1-3da95f601ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>اختبارات المادة</value>
      <webElementGuid>68f8e0df-052f-4da3-8bf0-ceb5e25f4c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r19:-trigger-quizzes&quot;)</value>
      <webElementGuid>c2c89dce-cdc2-4bff-ac48-679151a89f7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='radix-:r19:-trigger-quizzes']</value>
      <webElementGuid>442b754a-9fc8-460a-9ca3-6c3fbe7b3023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div[3]/div/a[3]</value>
      <webElementGuid>c07c97b2-b8c0-4874-82d3-3015f7e22eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'اختبارات المادة')]</value>
      <webElementGuid>2b4336d4-ccfd-4793-9a12-c85ecefe6acb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ملفات المادة'])[1]/following::a[1]</value>
      <webElementGuid>e6a9c4d7-5230-4129-9589-f9889b8582b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='فهرس الكتاب'])[2]/following::a[2]</value>
      <webElementGuid>edaa8210-c28e-445b-a92f-985247f00343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='دروس مجانية'])[1]/preceding::a[1]</value>
      <webElementGuid>db09feef-9b9d-47e2-ab89-4fcd478388e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الإنسان والصحة'])[1]/preceding::a[2]</value>
      <webElementGuid>d1a97483-dd35-42a4-84ad-2c72b023c652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='اختبارات المادة']/parent::*</value>
      <webElementGuid>290871bb-3e40-4c25-85ce-932c6d9392d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/e-school/%D8%A7%D9%84%D8%A3%D9%88%D9%84-%D9%81%D8%B5%D9%84-%D8%A3%D9%88%D9%84-%D8%A7%D9%84%D8%B9%D9%84%D9%88%D9%85/quizzes?grade=1')]</value>
      <webElementGuid>9b88e266-8b7d-4e27-a38f-ea4724825f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a[3]</value>
      <webElementGuid>55e2e3cc-51e7-431f-a181-1817b7a72c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@type = 'button' and @id = 'radix-:r19:-trigger-quizzes' and @href = '/e-school/%D8%A7%D9%84%D8%A3%D9%88%D9%84-%D9%81%D8%B5%D9%84-%D8%A3%D9%88%D9%84-%D8%A7%D9%84%D8%B9%D9%84%D9%88%D9%85/quizzes?grade=1' and (text() = 'اختبارات المادة' or . = 'اختبارات المادة')]</value>
      <webElementGuid>331d4268-d806-44b1-8da4-2c8441de4e61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
