<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>semesster 1</name>
   <tag></tag>
   <elementGuidId>16625bf6-0405-447c-acce-4775d40d5f8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;radix-:r1g:-trigger-semester-one&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Subject Image العلوم (ف1)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bb0892a8-4568-41c4-a4d3-825ce9e8d5b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-rounded-lg tw-border tw-border-slate-200 tw-bg-white tw-text-slate-950 tw-shadow-sm dark:tw-border-slate-800 dark:tw-bg-slate-950 dark:tw-text-slate-50 !tw-h-[190px] !tw-w-full !tw-rounded-[14px] tw-p-6 hover:tw-scale-105</value>
      <webElementGuid>2e710dde-0871-49d3-8468-3286afb09d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>العلوم(ف1)</value>
      <webElementGuid>d13153aa-602b-49f3-a9bd-e1f0e1077fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r16:-content-semester-one&quot;)/div[@class=&quot;tw-mt-6 tw-grid tw-grid-cols-1 tw-gap-x-5 tw-gap-y-8 xsm:tw-grid-cols-2 xsm:tw-justify-center sm:tw-grid-cols-2 md:tw-grid-cols-3 lg:tw-grid-cols-4 xl:tw-grid-cols-5 2xl:tw-justify-start 2xl:tw-gap-x-5&quot;]/a[1]/div[@class=&quot;tw-rounded-lg tw-border tw-border-slate-200 tw-bg-white tw-text-slate-950 tw-shadow-sm dark:tw-border-slate-800 dark:tw-bg-slate-950 dark:tw-text-slate-50 !tw-h-[190px] !tw-w-full !tw-rounded-[14px] tw-p-6 hover:tw-scale-105&quot;]</value>
      <webElementGuid>a6c0de44-3cb8-4f2a-aaec-59f1d2422135</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r16:-content-semester-one']/div/a/div</value>
      <webElementGuid>f37d305a-06a8-4ed3-8ae1-ffb098c4946b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='فصل ثاني'])[1]/following::div[3]</value>
      <webElementGuid>3eb41864-c98e-45a8-975e-bbf75cfdf7ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='فصل أول'])[1]/following::div[3]</value>
      <webElementGuid>a9009b12-0f09-4327-bdc6-357e1c8e65c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تذييل جو أكاديمي'])[1]/preceding::div[25]</value>
      <webElementGuid>6532d566-d98a-4195-be83-0c5a5bafd068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='روابط سريعة'])[1]/preceding::div[26]</value>
      <webElementGuid>a6fcdf7c-c583-4a84-8665-bfa4332f9ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/div</value>
      <webElementGuid>ab8d9faa-b085-4993-be77-1b7187841d8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'العلوم(ف1)' or . = 'العلوم(ف1)')]</value>
      <webElementGuid>00e15250-39b1-43b4-910c-75ea1da4799b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
