<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>semester one</name>
   <tag></tag>
   <elementGuidId>5a0563a7-b2f5-4704-be79-3a9b27890e59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='radix-:R1ajml6:-trigger-semester-one']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;فصل أول&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4d483aee-adab-4dd8-9508-b8910b44d8b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center justify-center whitespace-nowrap rounded-sm px-3 py-1.5 text-sm font-medium ring-offset-background transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 data-[state=active]:bg-background data-[state=active]:text-foreground data-[state=active]:shadow-sm tw-h-[48px] !tw-w-full tw-rounded-2xl tw-bg-[#6524BF] tw-text-white !tw-bg-gradient-to-b !tw-from-[#F2BF27] !tw-to-[#D17B0E] tw-flex tw-h-full tw-w-full tw-items-center tw-justify-center</value>
      <webElementGuid>e238db4c-d6a0-4708-8ffd-6ce833d16a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ab3a83a7-4875-4c1d-a06e-73754490eec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>70675717-961a-43b2-aec7-47931c1df619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b24fded9-725b-4914-8676-6a05f2f656b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:R1ajml6:-content-semester-one</value>
      <webElementGuid>be25e78e-21c2-4847-bd84-78a1319fe6d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>7a979ca4-1425-4e91-951f-9f7f49a5a4d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-:R1ajml6:-trigger-semester-one</value>
      <webElementGuid>cc14e92a-68df-4692-af7a-91f7a10d612c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>1304eeb9-90b9-4056-8726-a628f529b205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orientation</name>
      <type>Main</type>
      <value>horizontal</value>
      <webElementGuid>b053b569-693b-440b-858c-eb7ee057e77a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/e-school/y/%D8%A7%D9%84%D8%A3%D9%88%D9%84/semester-one?grade=1</value>
      <webElementGuid>dbc5957c-eb0a-4dad-879c-e344ead9e0f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>فصل أول</value>
      <webElementGuid>c7a81dee-a2f0-475a-a814-b0ac2ba0d166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:R1ajml6:-trigger-semester-one&quot;)</value>
      <webElementGuid>da22ae52-c16e-4408-a402-15abf59ad8a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='radix-:R1ajml6:-trigger-semester-one']</value>
      <webElementGuid>7571bed9-8761-4b3e-a5fd-ad9b18b55a60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/div/div/div[2]/div/a</value>
      <webElementGuid>fbfb4f96-2b4d-4b6f-81f9-bc13d6868c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'فصل أول')]</value>
      <webElementGuid>21570809-e592-4aae-a45c-1e642f494cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='هنا سوف تشاهد جميع موادك الدراسية'])[1]/following::a[1]</value>
      <webElementGuid>f1d1cddc-401c-4c9e-bf2f-d97d00082a1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='هيا نتعلم مع جو اكاديمي'])[1]/following::a[1]</value>
      <webElementGuid>a1a3868c-86d6-4725-9559-ca744bcc0286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='فصل ثاني'])[1]/preceding::a[1]</value>
      <webElementGuid>5aad5456-2689-4f44-87b6-f675e671d9f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تذييل جو أكاديمي'])[1]/preceding::a[10]</value>
      <webElementGuid>27845555-8496-4589-8d83-a479bc4d3991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='فصل أول']/parent::*</value>
      <webElementGuid>3586e12b-ac17-448b-8949-3c8ba8dd58a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/e-school/y/%D8%A7%D9%84%D8%A3%D9%88%D9%84/semester-one?grade=1')]</value>
      <webElementGuid>712621dd-74b0-4fb6-a175-6e388174e134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/a</value>
      <webElementGuid>edaf44fb-b792-4fab-ba03-36e83da337bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@type = 'button' and @id = 'radix-:R1ajml6:-trigger-semester-one' and @href = '/e-school/y/%D8%A7%D9%84%D8%A3%D9%88%D9%84/semester-one?grade=1' and (text() = 'فصل أول' or . = 'فصل أول')]</value>
      <webElementGuid>97739bd0-12db-47c7-8494-b2422d6ddb36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
