<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__63567</name>
   <tag></tag>
   <elementGuidId>057d5c97-f8be-4ac5-86b9-5b67fd7c874a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#63567</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='63567']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;\36 3567&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1b752506-e0d0-4207-8d94-7c79cbf44577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3e58c311-f8c9-4dcd-b982-871d155b61c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ed40f309-7765-49b8-899a-a65d3764faf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>079db035-db9e-4b99-89d0-85a7ed1ddcdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>unchecked</value>
      <webElementGuid>7cbd039d-ca3f-4241-b776-e9b79c44b85f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>63567</value>
      <webElementGuid>18cd1b8c-c368-480a-aa7b-711738129c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-aspect-square tw-h-4 tw-w-4 tw-rounded-full tw-border tw-border-slate-900 tw-text-slate-900 tw-ring-offset-white focus:tw-outline-none focus-visible:tw-ring-2 focus-visible:tw-ring-slate-950 focus-visible:tw-ring-offset-2 disabled:tw-cursor-not-allowed disabled:tw-opacity-50 dark:tw-border-slate-800 dark:tw-text-slate-50 dark:tw-ring-offset-slate-950 dark:focus-visible:tw-ring-slate-300 tw-h-[18px] tw-w-[18px] tw-cursor-pointer tw-rounded-full tw-pt-[1px] tw-text-blue-700 tw-shadow-black tw-outline-black tw-bg-white !tw-w-6 !tw-h-6 tw-border-[2px] tw-pb-[2px] disabled:tw-opacity-90</value>
      <webElementGuid>df917b05-f59a-4cce-a53e-a40c683c9fa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>63567</value>
      <webElementGuid>818a3514-6ad2-44f5-93f6-ce4103ab3b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>db7637a4-34b0-4f6c-9a66-00f439965196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;63567&quot;)</value>
      <webElementGuid>289bc5ae-c6b1-4b2f-8e01-dd2864818e7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='63567']</value>
      <webElementGuid>d19818aa-60b4-4ef3-82be-d173f0180c6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div[5]/div/div/div[4]/div/div[3]/div/div/div/div/button</value>
      <webElementGuid>72fee0a1-3095-4dc2-b360-bf33f97e7167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[3]/div/div/div/div/button</value>
      <webElementGuid>59c3d96f-04b3-4c68-803b-628e5698edd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = '63567']</value>
      <webElementGuid>c45d2046-f27f-4e9a-9122-d0b264d316c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
