<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__63561</name>
   <tag></tag>
   <elementGuidId>3a86d86b-6407-46db-a63e-4efe9793de5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#63561</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='63561']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;\36 3561&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5db8d777-977f-4d47-955f-43020cbac4e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f2a55130-1130-4e20-b446-c942da59d8b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>579c041d-9358-4216-ac9a-55463e0b7800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8531d7cc-c16f-460b-bf2f-4b674f361a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>unchecked</value>
      <webElementGuid>8527b3cf-17b3-48bb-8614-18de83772109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>63561</value>
      <webElementGuid>00301f18-2607-40af-95dd-9480ed16cea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-aspect-square tw-h-4 tw-w-4 tw-rounded-full tw-border tw-border-slate-900 tw-text-slate-900 tw-ring-offset-white focus:tw-outline-none focus-visible:tw-ring-2 focus-visible:tw-ring-slate-950 focus-visible:tw-ring-offset-2 disabled:tw-cursor-not-allowed disabled:tw-opacity-50 dark:tw-border-slate-800 dark:tw-text-slate-50 dark:tw-ring-offset-slate-950 dark:focus-visible:tw-ring-slate-300 tw-h-[18px] tw-w-[18px] tw-cursor-pointer tw-rounded-full tw-pt-[1px] tw-text-blue-700 tw-shadow-black tw-outline-black tw-bg-white !tw-w-6 !tw-h-6 tw-border-[2px] tw-pb-[2px] disabled:tw-opacity-90</value>
      <webElementGuid>0a576dd2-bd2b-4a37-a0ec-9e3e070392f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>63561</value>
      <webElementGuid>b2ad3a24-95c0-4feb-ab1b-3d1a26465510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5c181c51-c2e6-4097-af0d-82a3cdb26e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;63561&quot;)</value>
      <webElementGuid>f6b74578-9837-4e9a-b1df-f11c1ceba9bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='63561']</value>
      <webElementGuid>bcd20029-e662-4322-9305-229b4a28c015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div[5]/div/div/div/div/div[3]/div/div/div/div/button</value>
      <webElementGuid>4ac10326-1bbd-4f91-9e68-25903ff59af2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/button</value>
      <webElementGuid>01f9a5ae-f8cd-4a2e-a9c9-28ac2ecf2a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = '63561']</value>
      <webElementGuid>d645c388-0efc-4579-bb5f-3a7377edfa9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
