<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__63583</name>
   <tag></tag>
   <elementGuidId>7c2b57c8-fe19-48e0-abed-680f763508c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#63583</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='63583']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;\36 3583&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e6c49122-e234-415c-8259-1beee1b17b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3e0dfe2a-e7e2-4435-9418-dfb7f1dadd35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0539ac31-7dc6-442e-90bf-84c899d63002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b68d7253-6415-418f-8a66-6f0fd702fc77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>unchecked</value>
      <webElementGuid>a2fa6a3a-da17-4513-b439-b4238a46bed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>63583</value>
      <webElementGuid>c7dd675c-f243-4fca-8fe5-b1992e04a98a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-aspect-square tw-h-4 tw-w-4 tw-rounded-full tw-border tw-border-slate-900 tw-text-slate-900 tw-ring-offset-white focus:tw-outline-none focus-visible:tw-ring-2 focus-visible:tw-ring-slate-950 focus-visible:tw-ring-offset-2 disabled:tw-cursor-not-allowed disabled:tw-opacity-50 dark:tw-border-slate-800 dark:tw-text-slate-50 dark:tw-ring-offset-slate-950 dark:focus-visible:tw-ring-slate-300 tw-h-[18px] tw-w-[18px] tw-cursor-pointer tw-rounded-full tw-pt-[1px] tw-text-blue-700 tw-shadow-black tw-outline-black tw-bg-white !tw-w-6 !tw-h-6 tw-border-[2px] tw-pb-[2px] disabled:tw-opacity-90</value>
      <webElementGuid>9cdb111b-6467-46ec-9008-4575969edc81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>63583</value>
      <webElementGuid>9a1f38c4-c2f5-4049-a785-69faed890b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>17c052ac-e5f4-42f5-8c64-01839feb0dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;63583&quot;)</value>
      <webElementGuid>5aa88d2a-9b09-4a5e-bd7e-42c306f6ad93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='63583']</value>
      <webElementGuid>41bb1afa-4179-473f-921d-a96d9ac2ee67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div[5]/div/div/div[12]/div/div[3]/div/div/div/div/button</value>
      <webElementGuid>53784927-0bd8-4a1d-9bd8-01b5ead0a188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div[3]/div/div/div/div/button</value>
      <webElementGuid>be0595b8-dfc7-4b68-ac53-a3cdef91449a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = '63583']</value>
      <webElementGuid>80891ee4-c6e6-4e59-a769-cb55ad50a60c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
