<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__63577</name>
   <tag></tag>
   <elementGuidId>8d92e683-355d-41b9-bf80-36ea4cf6c266</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#63577</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='63577']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;\36 3577&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4a543f5e-df04-401d-bca3-0630185dac1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cbe2f0e0-18ae-404d-a650-46e80547a835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>13d9397b-12eb-43ee-a5c6-901cbc27d513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c1e8344e-95e5-416f-8f57-98d7ed66a480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>unchecked</value>
      <webElementGuid>0d66d3e0-ff92-4487-a32c-90ab57e7528e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>63577</value>
      <webElementGuid>de682f35-4dc2-4353-a528-3a4a37d78db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-aspect-square tw-h-4 tw-w-4 tw-rounded-full tw-border tw-border-slate-900 tw-text-slate-900 tw-ring-offset-white focus:tw-outline-none focus-visible:tw-ring-2 focus-visible:tw-ring-slate-950 focus-visible:tw-ring-offset-2 disabled:tw-cursor-not-allowed disabled:tw-opacity-50 dark:tw-border-slate-800 dark:tw-text-slate-50 dark:tw-ring-offset-slate-950 dark:focus-visible:tw-ring-slate-300 tw-h-[18px] tw-w-[18px] tw-cursor-pointer tw-rounded-full tw-pt-[1px] tw-text-blue-700 tw-shadow-black tw-outline-black tw-bg-white !tw-w-6 !tw-h-6 tw-border-[2px] tw-pb-[2px] disabled:tw-opacity-90</value>
      <webElementGuid>5639bbfe-8166-48f3-a7d9-c4b815c05554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>63577</value>
      <webElementGuid>5a8d1db9-61e6-4b2f-a842-c3b63895295b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a1adb303-7c8b-4301-83b1-3b5f01a2b689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;63577&quot;)</value>
      <webElementGuid>1a4313f1-acb4-4f84-9223-11523d552695</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='63577']</value>
      <webElementGuid>b9c89d12-e923-4406-be01-22b10d871ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div[5]/div/div/div[9]/div/div[3]/div/div/div/div/button</value>
      <webElementGuid>61642615-00a1-47b9-91e7-21fceaa0fa5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[3]/div/div/div/div/button</value>
      <webElementGuid>2543e659-ca06-4b21-ad28-71e766c3161e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = '63577']</value>
      <webElementGuid>0008e712-f2d1-4440-90aa-dc24dfa34c25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
