<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__tw-h-full tw-w-full max-smtw-h-134px m_f99809</name>
   <tag></tag>
   <elementGuidId>7bad7c4d-b6a9-43bb-b364-40331900ccea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section/div[2]/a/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;اذهب الى  برنامج التوجيهي و الثانوي | جو اكاديمي&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dd7a9e93-c5dc-4e9e-9633-d724e0c4bdbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>برنامج التوجيهي و الثانوي Jo Academy | جو اكاديمي</value>
      <webElementGuid>b67dd78c-cff9-4492-a2e9-60986c41b4af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>7c106593-7ffb-4d81-8176-23b88c596db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>0b361679-cf93-43b4-a336-1fb67b8dd66a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>230</value>
      <webElementGuid>9c449d0c-0d6a-49d0-ae8d-92c6c6276d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>e482487e-f2e9-4b07-b460-562b20b3760b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>20a9fafa-b3e6-483e-9f3e-16f24ce36d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-h-full tw-w-full max-sm:tw-h-[134px] max-sm:tw-w-[72px] sm:tw-h-[134px] sm:tw-w-[72px] md:tw-h-[245px] md:tw-w-full</value>
      <webElementGuid>4a34af3b-1ae7-43f8-b148-742d6a57358a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://admin.joacademy.net/uploads/6723/2-tawjihi.png</value>
      <webElementGuid>573727de-9424-4d69-af05-607d965b0a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/section[1]/div[@class=&quot;tw-mt-2 tw-flex tw-flex-wrap tw-justify-center tw-gap-2 md:tw-gap-4 md:tw-p-4&quot;]/a[1]/div[@class=&quot;tw-relative  tw-flex tw-h-[214px] tw-w-[151px] tw-flex-col tw-items-center tw-justify-center  tw-rounded-lg  tw-duration-500 hover:tw--translate-y-6 max-sm:tw-h-[214px] max-sm:tw-w-[151px] md:tw-h-[391px] md:tw-w-[278px] tw-bg-[#0D2755]&quot;]/div[@class=&quot;tw-z-[1000]  md:tw-mt-8 md:tw-max-h-none md:tw-max-w-none&quot;]/img[@class=&quot;tw-h-full tw-w-full max-sm:tw-h-[134px] max-sm:tw-w-[72px] sm:tw-h-[134px] sm:tw-w-[72px] md:tw-h-[245px] md:tw-w-full&quot;]</value>
      <webElementGuid>1899f1a9-09c1-422d-88ab-23a48e71059e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/div[2]/a/div/div/img</value>
      <webElementGuid>51d4ecb7-bdd5-4cca-ac26-6a24eef11aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='برنامج التوجيهي و الثانوي Jo Academy | جو اكاديمي']</value>
      <webElementGuid>1a46bd75-62b4-4d66-b9d0-257bbc8eda1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>fb43a68f-0ab4-4a79-b049-e3e7ae1fcbd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'برنامج التوجيهي و الثانوي Jo Academy | جو اكاديمي' and @src = 'https://admin.joacademy.net/uploads/6723/2-tawjihi.png']</value>
      <webElementGuid>b6aaa0e1-14e8-4f68-b238-75d7f170a8ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
