<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p__1</name>
   <tag></tag>
   <elementGuidId>398ba224-4614-47f6-8ca2-db5f9f7b816d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.tw-text-base.bold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div/div/div[2]/button/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;مراجعة الاختبار&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>a1fccea8-c5a9-4bfc-a6fe-5a6f20067dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-text-base bold</value>
      <webElementGuid>791aeac7-00db-4868-a3ec-0967d3e31da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>مراجعة الاختبار</value>
      <webElementGuid>43be85fd-a477-40d5-b02b-73dd85af8701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;tw-flex tw-min-h-screen tw-w-full tw-flex-col tw-justify-between tw-bg-[#F9F9F9]&quot;]/div[@class=&quot;tw-w-full&quot;]/div[@class=&quot;tw-relative tw-flex tw-w-full&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-relative !tw-w-full tw-px-4 md:tw-px-[30px] lg:tw-px-[40px] 2xl:tw-px-[100px] tw-mx-auto tw-w-full lg:tw-w-[calc(100vw-280px)] !tw-overflow-hidden&quot;]/div[1]/div[@class=&quot;tw-flex tw-flex-col tw-gap-4 tw-items-center&quot;]/div[@class=&quot;tw-p-3 tw-rounded-[14px] tw-w-full tw-justify-center tw-flex md:tw-w-[538px] tw-mt-40 tw-mb-10 tw-bg-none&quot;]/div[@class=&quot;tw-rounded-lg tw-border tw-border-slate-200 tw-bg-white tw-text-slate-950 tw-shadow-sm dark:tw-border-slate-800 dark:tw-bg-slate-950 dark:tw-text-slate-50 tw-bg-[#FFFFFF] !tw-rounded-[14px] tw-flex tw-gap-20 tw-w-full tw-justify-center xsm:tw-w-[361px] tw-flex-col md:tw-w-[490px] tw-p-5 tw-border tw-border-[#C1C1C1]&quot;]/div[@class=&quot;tw-flex tw-gap-4 tw-flex-wrap xsm:tw-flex-nowrap tw-mb-2&quot;]/button[@class=&quot;tw-inline-flex tw-items-center tw-justify-center tw-whitespace-nowrap tw-rounded-md tw-text-sm tw-font-medium tw-ring-offset-white tw-transition-colors focus-visible:tw-outline-none focus-visible:tw-ring-2 focus-visible:tw-ring-slate-950 focus-visible:tw-ring-offset-2 disabled:tw-pointer-events-none disabled:tw-opacity-50 dark:tw-ring-offset-slate-950 dark:focus-visible:tw-ring-slate-300 tw-bg-slate-900 tw-text-slate-50 hover:tw-bg-slate-900/90 dark:tw-bg-slate-50 dark:tw-text-slate-900 dark:hover:tw-bg-slate-50/90 tw-h-11 tw-rounded-md tw-px-8 tw-pointer-events-auto !tw-rounded-lg !tw-border-none !tw-h-12 !tw-w-[300px] !tw-bg-[#1A428A]&quot;]/p[@class=&quot;tw-text-base bold&quot;]</value>
      <webElementGuid>8044ef2b-bad5-4433-9f34-31376a317406</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div/div/div[2]/button/p</value>
      <webElementGuid>7275389a-d8c2-4c66-b5a7-56e278d4b437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='فعاليات جو اكاديمي'])[1]/following::p[3]</value>
      <webElementGuid>dd50db36-72d0-4d97-a257-fbb727a4a780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='منح جواكاديمي'])[1]/following::p[3]</value>
      <webElementGuid>1508d51b-2981-4742-975a-92953e5d3c10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تذييل جو أكاديمي'])[1]/preceding::p[2]</value>
      <webElementGuid>e0fc93d1-0c27-45e7-8208-d4483d037ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='روابط سريعة'])[1]/preceding::p[2]</value>
      <webElementGuid>a38fd9cb-4db5-40f7-ab69-cd0f165e71ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='مراجعة الاختبار']/parent::*</value>
      <webElementGuid>06c29177-46df-4fb5-9728-c4b1ee472111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/p</value>
      <webElementGuid>dfff5531-9f85-418c-ad94-d6e38a14c271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'مراجعة الاختبار' or . = 'مراجعة الاختبار')]</value>
      <webElementGuid>7f9bba75-a3a2-48c4-bb5a-53ad6137dbd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
