<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>copy link share button</name>
   <tag></tag>
   <elementGuidId>733e588d-aaf0-4dc8-90fe-9f14f331bb3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;radix-:r1v:&quot;]/button[5]]/button&#xd;
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button i.ri-file-copy-fill.tw-text-[#1A428A]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;نسخ رابط الملفنسخ رابط الملف&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>49f449c5-6701-4977-a6d9-106ae85e41b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-side</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>fb5ef04d-6850-4647-9f7f-ef5fbbd0b5b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>f6a67e69-2bb2-4bb5-92b5-6e2db9e94d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>delayed-open</value>
      <webElementGuid>5ec012b4-79a8-4c84-ad7f-a7c5d4d33992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-z-50 tw-overflow-hidden tw-rounded-md tw-border tw-border-slate-200 tw-bg-[#262626] tw-px-3 tw-py-1.5 tw-text-sm tw-text-slate-50 tw-shadow-md tw-animate-in tw-fade-in-0 tw-zoom-in-95 data-[state=closed]:tw-animate-out data-[state=closed]:tw-fade-out-0 data-[state=closed]:tw-zoom-out-95 data-[side=bottom]:tw-slide-in-from-top-2 data-[side=left]:tw-slide-in-from-right-2 data-[side=right]:tw-slide-in-from-left-2 data-[side=top]:tw-slide-in-from-bottom-2 dark:tw-border-slate-800 dark:tw-bg-slate-950 dark:tw-text-slate-50</value>
      <webElementGuid>dc6a0d04-b637-4695-8a56-b5104667ba67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>نسخ رابط الملفنسخ رابط الملف</value>
      <webElementGuid>8d298526-681f-4241-bef7-10b58e415b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r18:&quot;)/div[1]/div[@class=&quot;tw-z-50 tw-overflow-hidden tw-rounded-md tw-border tw-border-slate-200 tw-bg-[#262626] tw-px-3 tw-py-1.5 tw-text-sm tw-text-slate-50 tw-shadow-md tw-animate-in tw-fade-in-0 tw-zoom-in-95 data-[state=closed]:tw-animate-out data-[state=closed]:tw-fade-out-0 data-[state=closed]:tw-zoom-out-95 data-[side=bottom]:tw-slide-in-from-top-2 data-[side=left]:tw-slide-in-from-right-2 data-[side=right]:tw-slide-in-from-left-2 data-[side=top]:tw-slide-in-from-bottom-2 dark:tw-border-slate-800 dark:tw-bg-slate-950 dark:tw-text-slate-50&quot;]</value>
      <webElementGuid>e5dbae15-e395-49c6-be7e-47345120b42f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r18:']/div/div</value>
      <webElementGuid>4da0bb6d-9a9d-476e-90fe-9cc49a2c3fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='صفحاتنا على مواقع التواصل الاجتماعي'])[1]/following::div[11]</value>
      <webElementGuid>43c715e3-4777-4842-b964-8eb5fc9015a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WINDOWS'])[1]/following::div[12]</value>
      <webElementGuid>2edf5e25-f4d9-44b7-8e99-a772fd14f429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='نسخ رابط الملف']/parent::*</value>
      <webElementGuid>a4f7eb6c-0a3a-4c19-a89d-21f64a4dbd63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>42e5783c-ac13-4e5b-a298-f28e301269bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'نسخ رابط الملفنسخ رابط الملف' or . = 'نسخ رابط الملفنسخ رابط الملف')]</value>
      <webElementGuid>13a7a08c-c0ef-4e03-a392-3563308227e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
