<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>copy link share button</name>
   <tag></tag>
   <elementGuidId>733e588d-aaf0-4dc8-90fe-9f14f331bb3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button i.ri-file-copy-fill.tw-text-[#1A428A]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:r18:']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;نسخ رابط الملفنسخ رابط الملف&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>471c72f9-ed8a-4d07-a610-1a1818be7fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-side</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>3c7b38d2-818e-49d3-b411-76c79880ce55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>7bd2d9d6-3466-4faf-b370-0d732282dd7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>delayed-open</value>
      <webElementGuid>e6199859-18cf-426a-8c68-dac8974d883b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-z-50 tw-overflow-hidden tw-rounded-md tw-border tw-border-slate-200 tw-bg-[#262626] tw-px-3 tw-py-1.5 tw-text-sm tw-text-slate-50 tw-shadow-md tw-animate-in tw-fade-in-0 tw-zoom-in-95 data-[state=closed]:tw-animate-out data-[state=closed]:tw-fade-out-0 data-[state=closed]:tw-zoom-out-95 data-[side=bottom]:tw-slide-in-from-top-2 data-[side=left]:tw-slide-in-from-right-2 data-[side=right]:tw-slide-in-from-left-2 data-[side=top]:tw-slide-in-from-bottom-2 dark:tw-border-slate-800 dark:tw-bg-slate-950 dark:tw-text-slate-50</value>
      <webElementGuid>d692d29a-4dc1-4e61-b5f4-afb909cb0d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>نسخ رابط الملفنسخ رابط الملف</value>
      <webElementGuid>4f4fb519-140e-4a87-85e1-34cc7367f8b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r18:&quot;)/div[1]/div[@class=&quot;tw-z-50 tw-overflow-hidden tw-rounded-md tw-border tw-border-slate-200 tw-bg-[#262626] tw-px-3 tw-py-1.5 tw-text-sm tw-text-slate-50 tw-shadow-md tw-animate-in tw-fade-in-0 tw-zoom-in-95 data-[state=closed]:tw-animate-out data-[state=closed]:tw-fade-out-0 data-[state=closed]:tw-zoom-out-95 data-[side=bottom]:tw-slide-in-from-top-2 data-[side=left]:tw-slide-in-from-right-2 data-[side=right]:tw-slide-in-from-left-2 data-[side=top]:tw-slide-in-from-bottom-2 dark:tw-border-slate-800 dark:tw-bg-slate-950 dark:tw-text-slate-50&quot;]</value>
      <webElementGuid>9a58192b-29f5-4ccb-82c5-719e591d9c14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r18:']/div/div</value>
      <webElementGuid>a5d459c1-0da0-45b7-b0f8-62273768001f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='صفحاتنا على مواقع التواصل الاجتماعي'])[1]/following::div[11]</value>
      <webElementGuid>09659cec-bbc2-4cd3-8eec-067da2e7511c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WINDOWS'])[1]/following::div[12]</value>
      <webElementGuid>f8f63896-b246-417b-ad77-775e23ed85aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='نسخ رابط الملف']/parent::*</value>
      <webElementGuid>1f2d20d2-1505-46b6-a642-2c6d12ddce24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>2321f366-4028-4fb2-8616-adc13bf220d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'نسخ رابط الملفنسخ رابط الملف' or . = 'نسخ رابط الملفنسخ رابط الملف')]</value>
      <webElementGuid>96cbafeb-3998-4a63-b454-9eaba69dbfb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
