<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>share the link on social media</name>
   <tag></tag>
   <elementGuidId>17d178b8-8702-4aba-b892-68b64df51095</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>body div[data-radix-popper-content-wrapper=''][style='position: fixed; left: 0px; top: 0px; transform: translate(259.2px, 407.2px); min-width: max-content; z-index: 50; --radix-popper-available-width: 1057.5999755859375px; --radix-popper-available-height: 449.3999938964844px; --radix-popper-anchor-width: 167.5px; --radix-popper-anchor-height: 40px; --radix-popper-transform-origin: 50% 42.4px;'] div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;radix-:r20:&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=dialog</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a6772e7c-2a52-471b-aac2-1be5b6a817d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-side</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>3b03dd51-4d3e-448d-8024-ae352482453d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>c15d44e0-34d1-4e03-8b33-6fd9d39d856c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>open</value>
      <webElementGuid>0c48624d-c441-4cbf-a32f-0a2404772dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>f6d21638-ac0c-425e-a6cd-8ee08cf0bbdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-:r18:</value>
      <webElementGuid>152e96d6-6b78-4b2f-a7fa-60821a0f7409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-z-50 tw-w-72 tw-rounded-[10px] tw-border-[1px] tw-border-solid tw-border-[#ececec] tw-bg-white tw-p-4 tw-outline-none data-[state=open]:tw-animate-in data-[state=closed]:tw-animate-out data-[state=closed]:tw-fade-out-0 data-[state=open]:tw-fade-in-0 data-[state=closed]:tw-zoom-out-95 data-[state=open]:tw-zoom-in-95 data-[side=bottom]:tw-slide-in-from-top-2 data-[side=left]:tw-slide-in-from-right-2 data-[side=right]:tw-slide-in-from-left-2 data-[side=top]:tw-slide-in-from-bottom-2 tw-inline-flex tw-w-full tw-gap-[10px] tw-bg-[#F8F6F6] tw-p-[5px] tw-text-[20px]</value>
      <webElementGuid>886980e3-4aa2-4b49-bb42-cebe4d5aab71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>14ffffdf-38f8-4520-aa18-35c9e3c7525d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r18:&quot;)</value>
      <webElementGuid>a60ad9c5-2fd9-46c9-b952-49a3e3d99767</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='radix-:r18:']</value>
      <webElementGuid>c56222fb-49f8-4894-8a50-e2c4ced0cb03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='صفحاتنا على مواقع التواصل الاجتماعي'])[1]/following::div[9]</value>
      <webElementGuid>136eba77-8bc3-4c57-b891-cf01b6f4ffdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>fba68bbd-2ef5-4d34-8b59-74fe793a61f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'radix-:r18:']</value>
      <webElementGuid>7a6bc077-c377-42e4-9141-be9ea33b49f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
