<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>materila file button</name>
   <tag></tag>
   <elementGuidId>6793307b-cd56-493a-bb6c-eb67deca0268</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/div/div[3]/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;ملفات المادة&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1b3e6171-d805-4ff1-8069-4d9f17c722d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center justify-center whitespace-nowrap rounded-sm px-3 py-1.5 text-sm font-medium ring-offset-background transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 data-[state=active]:bg-background data-[state=active]:text-foreground data-[state=active]:shadow-sm tw-h-[40px] max-md:!tw-text-[14px] max-md:tw-px-2 tw-whitespace-nowrap md:!tw-mt-8 max-md:tw-relative max-md:!tw-w-full max-md:tw-border-b-4 max-md:tw-rounded-none data-[state=active]:after:tw-absolute data-[state=active]:after:-tw-bottom-[11px] !tw-bg-[#6524BF] max-lg:!tw-w-full bold tw-text-white max-md:tw-border-none !tw-rounded-[14px] !tw-drop-shadow-xl tw-text-lg lg:tw-p-1 lg:tw-px-6 !tw-bg-gradient-to-b !tw-from-[#F2BF27] !tw-to-[#D17B0E] !tw-bg-transparent tw-flex tw-items-center tw-justify-center</value>
      <webElementGuid>85a47ddf-948a-4abb-a99b-0ae1b0beaebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>712e9435-435d-4b58-89c0-a82e89411044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>f4cefbac-9c9f-45f2-89e2-1b058c59fa96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>063a640c-0018-4058-a94c-87c255125438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:r1:-content-subject-files</value>
      <webElementGuid>0e235c1f-c21f-443c-b5ca-5079c2faad61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>9483d233-1166-4961-a049-42401ed1ff59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-:r1:-trigger-subject-files</value>
      <webElementGuid>1f5e7378-a2bf-40c6-b27b-3bd0b547222f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e1ba6fce-d884-4878-a5fb-fc9f31f427de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orientation</name>
      <type>Main</type>
      <value>horizontal</value>
      <webElementGuid>cbaaad43-88d3-438b-9c39-02d14c9598d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/e-school/%D8%A7%D9%84%D8%B1%D8%A7%D8%A8%D8%B9-%D9%81%D8%B5%D9%84-%D8%A3%D9%88%D9%84-%D8%A7%D9%84%D8%B9%D9%84%D9%88%D9%85/subject-files?grade=4</value>
      <webElementGuid>80b65d6b-2a6a-48eb-bbe1-ed9c84c4187c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ملفات المادة</value>
      <webElementGuid>e298b452-09de-4bf0-ac74-b81c2a59125c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r1:-trigger-subject-files&quot;)</value>
      <webElementGuid>5d2141ce-8c03-40fc-bd15-171ef8de61e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='radix-:r1:-trigger-subject-files']</value>
      <webElementGuid>70100c1e-b293-4130-a76a-9bd88b821fad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/div/div/div[3]/div/a[2]</value>
      <webElementGuid>afa4f956-cff3-46c5-9dd7-8f0b733ec0f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'ملفات المادة')])[2]</value>
      <webElementGuid>e78cf03b-8f6b-484f-9449-9f6c28afad78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='فهرس الكتاب'])[1]/following::a[1]</value>
      <webElementGuid>d92f7223-857a-444a-baf0-d02bbf6d1e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ملفات المادة'])[1]/following::a[2]</value>
      <webElementGuid>ba52b3b6-0eab-462e-85a2-e0b7d96f0997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اختبارات المادة'])[1]/preceding::a[1]</value>
      <webElementGuid>07fb736b-67c8-443a-9066-df8820b3e3a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='دروس مجانية'])[1]/preceding::a[2]</value>
      <webElementGuid>5f23bc8c-b859-46fb-9e67-3177ee3db4ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/e-school/%D8%A7%D9%84%D8%B1%D8%A7%D8%A8%D8%B9-%D9%81%D8%B5%D9%84-%D8%A3%D9%88%D9%84-%D8%A7%D9%84%D8%B9%D9%84%D9%88%D9%85/subject-files?grade=4')]</value>
      <webElementGuid>dc324b5b-b25f-4553-935f-b047053f25d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div/a[2]</value>
      <webElementGuid>c46c4bcc-64d0-4247-8ace-1a25a370ad7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@type = 'button' and @id = 'radix-:r1:-trigger-subject-files' and @href = '/e-school/%D8%A7%D9%84%D8%B1%D8%A7%D8%A8%D8%B9-%D9%81%D8%B5%D9%84-%D8%A3%D9%88%D9%84-%D8%A7%D9%84%D8%B9%D9%84%D9%88%D9%85/subject-files?grade=4' and (text() = 'ملفات المادة' or . = 'ملفات المادة')]</value>
      <webElementGuid>0d0bd7ba-c749-4061-8668-5c7dfa9a7f43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
