<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>abstract-sheet</name>
   <tag></tag>
   <elementGuidId>c1098c08-1474-4582-b7c5-598ce9d5b75b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='radix-:rb:-trigger-abstract-sheet']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;الملخص&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bf93c407-6b98-44a5-8f42-c2e38c69df22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center justify-center whitespace-nowrap rounded-sm px-3 py-1.5 text-sm font-medium ring-offset-background transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 data-[state=active]:bg-background data-[state=active]:text-foreground data-[state=active]:shadow-sm tw-h-[64px] tw-whitespace-nowrap tw-text-lg tw-text-white max-md:tw-border-none medium max-md:!tw-p-2 max-md:!tw-rounded-[14px] max-md:!tw-min-w-[112px] max-md:!tw-h-[48px] max-md:tw-text-[14px] !tw-bg-[#51C279] bold !tw-w-full max-md:tw-bg-[#DCEAFF] data-[state=active]:after:tw-absolute data-[state=active]:after:-tw-bottom-[11px] tw-rounded-br-[14px] tw-border-b-4 data-[state=active]:tw-border-[#1A428A] max-md:data-[state=active]:tw-bg-[#1A428A] max-md:data-[state=active]:!tw-text-white tw-flex tw-w-full tw-items-center tw-justify-center</value>
      <webElementGuid>fba276df-202a-44df-9bbd-d309c919668a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>77d305b2-3dcf-43f9-aa7e-181c8a8efa76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>52966d8d-99ad-4c45-97e0-349457adb1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b52b024c-92e0-48ef-b233-115fdc5ae0ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:rb:-content-abstract-sheet</value>
      <webElementGuid>99b9daea-5c45-4284-86c1-c8658cff5291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>inactive</value>
      <webElementGuid>6ec770ee-734b-41d0-9ae1-26b9c125b506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-:rb:-trigger-abstract-sheet</value>
      <webElementGuid>159cd194-11b4-4a47-9495-32f7678c25c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fa072fc6-301d-4f06-9c43-695a52e5ad9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orientation</name>
      <type>Main</type>
      <value>horizontal</value>
      <webElementGuid>77b23d81-04b4-4596-9f42-06482afc8a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/e-school/lesson/%D9%86%D9%8E%D8%AD%D9%92%D9%86%D9%8F-%D9%85%D9%8F%D8%AA%D8%B4%D8%A7%D8%A8%D9%90%D9%87%D9%88%D9%86-2016/abstract-sheet?grade=1</value>
      <webElementGuid>e1e6eb86-04d3-4d03-b951-8d472107a345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>الملخص</value>
      <webElementGuid>117e5fac-7860-47a6-8cbb-eac780d079d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:rb:-trigger-abstract-sheet&quot;)</value>
      <webElementGuid>c8bc252f-8768-4d5e-93db-e545771cf1f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='radix-:rb:-trigger-abstract-sheet']</value>
      <webElementGuid>18a82239-5a50-4b9b-aa4c-987082bf16ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/div/div/div[3]/div/div/div/a[2]</value>
      <webElementGuid>afe31cb9-7d0c-410e-8f6c-3bd7a2e47443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'الملخص')]</value>
      <webElementGuid>e0c1cc17-985b-456c-b674-8d6cf721de2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الشرح'])[2]/following::a[1]</value>
      <webElementGuid>7fcf3db1-62e7-4ff6-90b1-851d332912a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الشرح'])[1]/following::a[3]</value>
      <webElementGuid>eea59fcd-c79e-47a4-93dc-dc658d769a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='أوراق العمل'])[1]/preceding::a[1]</value>
      <webElementGuid>204777a4-ad65-4331-92af-4db88e808e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حل اسئلة الدرس'])[1]/preceding::a[2]</value>
      <webElementGuid>65c50826-581e-4565-8ac8-c3dc3353ea72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='الملخص']/parent::*</value>
      <webElementGuid>4edfa688-7c2e-4672-af98-f9695ce7d583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/e-school/lesson/%D9%86%D9%8E%D8%AD%D9%92%D9%86%D9%8F-%D9%85%D9%8F%D8%AA%D8%B4%D8%A7%D8%A8%D9%90%D9%87%D9%88%D9%86-2016/abstract-sheet?grade=1')]</value>
      <webElementGuid>d8a123f2-fc9e-437a-af03-23de48530e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/a[2]</value>
      <webElementGuid>8994bf4c-dc3d-40ce-ad2b-18b364a5ac1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@type = 'button' and @id = 'radix-:rb:-trigger-abstract-sheet' and @href = '/e-school/lesson/%D9%86%D9%8E%D8%AD%D9%92%D9%86%D9%8F-%D9%85%D9%8F%D8%AA%D8%B4%D8%A7%D8%A8%D9%90%D9%87%D9%88%D9%86-2016/abstract-sheet?grade=1' and (text() = 'الملخص' or . = 'الملخص')]</value>
      <webElementGuid>78eeeb43-fbde-403d-84dd-20740ed2d613</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
