<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>explanation</name>
   <tag></tag>
   <elementGuidId>0be531d1-375c-48f8-8b67-cd9a84082eb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='radix-:rb:-trigger-explanation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;الشرح&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>de9de370-7ef8-4613-8edc-503223716ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center justify-center whitespace-nowrap rounded-sm px-3 py-1.5 text-sm font-medium ring-offset-background transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 data-[state=active]:bg-background data-[state=active]:text-foreground data-[state=active]:shadow-sm tw-h-[64px] tw-whitespace-nowrap tw-text-lg tw-text-white max-md:tw-border-none medium max-md:!tw-p-2 max-md:!tw-rounded-[14px] max-md:!tw-min-w-[112px] max-md:!tw-h-[48px] max-md:tw-text-[14px] !tw-bg-[#51C279] bold !tw-w-full max-md:tw-bg-[#DCEAFF] data-[state=active]:after:tw-absolute data-[state=active]:after:-tw-bottom-[11px] data-[state=active]:!tw-bg-white !tw-border-none data-[state=active]:!tw-text-[#D17B0E] max-md:data-[state=active]:!tw-bg-[#257040] max-md:data-[state=active]:!tw-text-white tw-flex tw-w-full tw-items-center tw-justify-center</value>
      <webElementGuid>e4d4535c-a612-4c42-83ad-b3c7164103bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>497e06d4-fc01-4ca7-b048-9f637531307b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>547b3504-5caf-4465-9391-72bb5cb5be68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>88c079f0-5016-4159-bf66-c63d07d8198d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:rb:-content-explanation</value>
      <webElementGuid>f20a29e6-0056-40b5-aa22-9ed751102bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>82d3f126-d72e-4c91-97ad-8ffb4da30ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-:rb:-trigger-explanation</value>
      <webElementGuid>ea750ab1-9c2e-4778-ba7e-f46ebe394d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7ef24bbb-1a07-42c2-b5ad-9bff0eef4e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orientation</name>
      <type>Main</type>
      <value>horizontal</value>
      <webElementGuid>d475ef18-8c5c-4de8-bf3c-fa2a9f033e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/e-school/lesson/%D9%86%D9%8E%D8%AD%D9%92%D9%86%D9%8F-%D9%85%D9%8F%D8%AA%D8%B4%D8%A7%D8%A8%D9%90%D9%87%D9%88%D9%86-2016/explanation?grade=1</value>
      <webElementGuid>286f2b03-2103-42e5-b8d6-fb7659982610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>الشرح</value>
      <webElementGuid>6cd63afe-6a09-4f5b-85f7-fb4669ee4a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:rb:-trigger-explanation&quot;)</value>
      <webElementGuid>843ee5aa-5c96-4dc0-b910-f9b3119eb275</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='radix-:rb:-trigger-explanation']</value>
      <webElementGuid>e0edd40f-0f6c-439e-ba1f-fbd5d5c7bd35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/div/div/div[3]/div/div/div/a</value>
      <webElementGuid>21d1e277-a3f7-4ecf-916f-0c0feaa1af5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'الشرح')])[2]</value>
      <webElementGuid>55115c8b-a1a2-4f7b-847f-14fe6a568515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الشرح'])[1]/following::a[2]</value>
      <webElementGuid>4b1ecf6d-cf14-4f36-bee6-56a226c61c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='نَحْنُ مُتشابِهون'])[1]/following::a[3]</value>
      <webElementGuid>420d4f1e-c49a-46e5-bae1-91b53dbc0a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الملخص'])[1]/preceding::a[1]</value>
      <webElementGuid>46c0606c-8d2f-4479-9c73-5d4c987112c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='أوراق العمل'])[1]/preceding::a[2]</value>
      <webElementGuid>e298fcec-abc6-41cc-b0e9-132026524b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/e-school/lesson/%D9%86%D9%8E%D8%AD%D9%92%D9%86%D9%8F-%D9%85%D9%8F%D8%AA%D8%B4%D8%A7%D8%A8%D9%90%D9%87%D9%88%D9%86-2016/explanation?grade=1')]</value>
      <webElementGuid>c4623ca8-fa38-472d-8fd3-a73e14a98228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/a</value>
      <webElementGuid>707745ee-32a8-481d-b357-74ab6e0ff1bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@type = 'button' and @id = 'radix-:rb:-trigger-explanation' and @href = '/e-school/lesson/%D9%86%D9%8E%D8%AD%D9%92%D9%86%D9%8F-%D9%85%D9%8F%D8%AA%D8%B4%D8%A7%D8%A8%D9%90%D9%87%D9%88%D9%86-2016/explanation?grade=1' and (text() = 'الشرح' or . = 'الشرح')]</value>
      <webElementGuid>c86f3b7b-2983-4003-ab2e-c6d03b08522c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
