<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lesson-question</name>
   <tag></tag>
   <elementGuidId>0e883007-b3b6-4b3f-a9ca-a00262947e09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='radix-:rb:-trigger-lesson-question']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;حل اسئلة الدرس&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a3d55c31-3a34-4a58-ad9e-cae1780bc5bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center justify-center whitespace-nowrap rounded-sm px-3 py-1.5 text-sm font-medium ring-offset-background transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 data-[state=active]:bg-background data-[state=active]:text-foreground data-[state=active]:shadow-sm tw-h-[64px] tw-whitespace-nowrap tw-text-lg tw-text-white max-md:tw-border-none medium max-md:!tw-p-2 max-md:!tw-rounded-[14px] max-md:!tw-min-w-[112px] max-md:!tw-h-[48px] max-md:tw-text-[14px] !tw-bg-[#51C279] bold !tw-w-full max-md:tw-bg-[#DCEAFF] data-[state=active]:after:tw-absolute data-[state=active]:after:-tw-bottom-[11px] tw-rounded-br-[14px] tw-border-b-4 data-[state=active]:tw-border-[#1A428A] max-md:data-[state=active]:tw-bg-[#1A428A] max-md:data-[state=active]:!tw-text-white tw-flex tw-w-full tw-items-center tw-justify-center</value>
      <webElementGuid>5f590d73-0263-4eb9-a7da-6e050666e08b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b45911f3-1862-4a5a-968d-e75c30baac8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>65a99c77-948e-4dac-9cfb-e18420bc41f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c1235e21-499c-4d28-abae-f6f3e03a6ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:rb:-content-lesson-question</value>
      <webElementGuid>14c69c32-8abc-4727-bd2c-6e88ac7f2997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>inactive</value>
      <webElementGuid>3d016e23-4486-4d12-8d15-adf44316c642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-:rb:-trigger-lesson-question</value>
      <webElementGuid>ae64d628-c472-430d-ac56-330bafef1860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7c59fc53-0dab-4988-8021-ef4885e75c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orientation</name>
      <type>Main</type>
      <value>horizontal</value>
      <webElementGuid>105bc3d4-5af4-4e4e-9c49-5baf05e174da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/e-school/lesson/%D9%86%D9%8E%D8%AD%D9%92%D9%86%D9%8F-%D9%85%D9%8F%D8%AA%D8%B4%D8%A7%D8%A8%D9%90%D9%87%D9%88%D9%86-2016/lesson-question?grade=1</value>
      <webElementGuid>293c7ea9-b44e-47e2-9a9e-044d87f529dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>حل اسئلة الدرس</value>
      <webElementGuid>02192e44-f7fe-40db-acdd-d7111337cdd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:rb:-trigger-lesson-question&quot;)</value>
      <webElementGuid>8f58d03e-2ea8-43b2-92dc-71e05322e33a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='radix-:rb:-trigger-lesson-question']</value>
      <webElementGuid>27bf2a56-2790-43d3-9022-0cef4ee7040b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/div/div/div[3]/div/div/div/a[4]</value>
      <webElementGuid>273d4434-e972-42da-9f38-3d151892f579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'حل اسئلة الدرس')]</value>
      <webElementGuid>3a9917e5-959a-41be-97bb-a572a43c2724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='أوراق العمل'])[2]/following::a[1]</value>
      <webElementGuid>6330eb1c-fb5f-4086-9c62-93884c7f65f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الملخص'])[1]/following::a[2]</value>
      <webElementGuid>34075016-26cd-4fad-9796-4282b496bf98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='النتاجات'])[1]/preceding::a[1]</value>
      <webElementGuid>bce8e54f-6f4d-4b1f-8b86-9680afea6dd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='نَحْنُ مُتشابِهون'])[2]/preceding::a[2]</value>
      <webElementGuid>67e382da-bdca-453b-aedf-94891603449e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='حل اسئلة الدرس']/parent::*</value>
      <webElementGuid>3ee20197-0edb-4473-9654-0de4b0c7acd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/e-school/lesson/%D9%86%D9%8E%D8%AD%D9%92%D9%86%D9%8F-%D9%85%D9%8F%D8%AA%D8%B4%D8%A7%D8%A8%D9%90%D9%87%D9%88%D9%86-2016/lesson-question?grade=1')]</value>
      <webElementGuid>fb0ab49e-63b2-4b55-a3b7-94d3a6e8b742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/a[4]</value>
      <webElementGuid>f6abb01a-e9ca-4389-b9c8-d49ea9f0a53d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@type = 'button' and @id = 'radix-:rb:-trigger-lesson-question' and @href = '/e-school/lesson/%D9%86%D9%8E%D8%AD%D9%92%D9%86%D9%8F-%D9%85%D9%8F%D8%AA%D8%B4%D8%A7%D8%A8%D9%90%D9%87%D9%88%D9%86-2016/lesson-question?grade=1' and (text() = 'حل اسئلة الدرس' or . = 'حل اسئلة الدرس')]</value>
      <webElementGuid>41c758f3-c811-4521-af19-ce4985c52701</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
