<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>work-sheets</name>
   <tag></tag>
   <elementGuidId>15dc4cf6-ccbe-4655-8be4-b526d493f8a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='radix-:rb:-trigger-work-sheets']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;أوراق العمل&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ff3f364c-4320-4888-91a8-faddadaf15c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center justify-center whitespace-nowrap rounded-sm px-3 py-1.5 text-sm font-medium ring-offset-background transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 data-[state=active]:bg-background data-[state=active]:text-foreground data-[state=active]:shadow-sm tw-h-[64px] tw-whitespace-nowrap tw-text-lg tw-text-white max-md:tw-border-none medium max-md:!tw-p-2 max-md:!tw-rounded-[14px] max-md:!tw-min-w-[112px] max-md:!tw-h-[48px] max-md:tw-text-[14px] !tw-bg-[#51C279] bold !tw-w-full max-md:tw-bg-[#DCEAFF] data-[state=active]:after:tw-absolute data-[state=active]:after:-tw-bottom-[11px] tw-rounded-br-[14px] tw-border-b-4 data-[state=active]:tw-border-[#1A428A] max-md:data-[state=active]:tw-bg-[#1A428A] max-md:data-[state=active]:!tw-text-white tw-flex tw-w-full tw-items-center tw-justify-center</value>
      <webElementGuid>492f1dca-a0eb-4981-983a-68653d08d238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4dbf42e5-2504-4744-95b5-3d76b07c9236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>322e035c-9fea-40e5-97bb-3527c8a96fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b0a2c72b-11e0-4432-9390-cba491e4c936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:rb:-content-work-sheets</value>
      <webElementGuid>3f74d944-737f-4e30-9a89-37d571d3efa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>inactive</value>
      <webElementGuid>4252d667-99de-4346-9ecf-eb5c0d8feb19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-:rb:-trigger-work-sheets</value>
      <webElementGuid>bda830d3-195e-4e8d-8e4d-46c96b1755de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0855a128-dab9-4989-89c9-23a8fabd651f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orientation</name>
      <type>Main</type>
      <value>horizontal</value>
      <webElementGuid>52ebdd47-7440-493f-b3f4-62ac14ccc175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/e-school/lesson/%D9%86%D9%8E%D8%AD%D9%92%D9%86%D9%8F-%D9%85%D9%8F%D8%AA%D8%B4%D8%A7%D8%A8%D9%90%D9%87%D9%88%D9%86-2016/work-sheets?grade=1</value>
      <webElementGuid>62e0d5af-2b78-4e2e-ab6f-42f81e4e3cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>أوراق العمل</value>
      <webElementGuid>633a09ca-d0d6-4d50-b529-def67ae03bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:rb:-trigger-work-sheets&quot;)</value>
      <webElementGuid>3128808c-24eb-4b48-b1b5-ffc06ac1256a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='radix-:rb:-trigger-work-sheets']</value>
      <webElementGuid>5418f976-08fc-420f-9cfb-d2ec19d91997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/div/div/div[3]/div/div/div/a[3]</value>
      <webElementGuid>f2692bc1-760f-4a16-aec5-dda272cbc607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'أوراق العمل')]</value>
      <webElementGuid>bb6f0483-a5fa-41aa-839f-7e3c2246c6c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الملخص'])[2]/following::a[1]</value>
      <webElementGuid>274db3da-190e-4222-b8bb-cf6db16ecb25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الشرح'])[1]/following::a[2]</value>
      <webElementGuid>e5142076-2af9-4851-b45c-c96ba745b478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حل اسئلة الدرس'])[1]/preceding::a[1]</value>
      <webElementGuid>92e710d8-a5c5-404b-ad3b-0198e48bf04a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='النتاجات'])[1]/preceding::a[2]</value>
      <webElementGuid>96d11aab-154f-4ce9-b5ca-36178bb90f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='أوراق العمل']/parent::*</value>
      <webElementGuid>ca5d155f-0711-4d2e-8a36-1b86c182c3ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/e-school/lesson/%D9%86%D9%8E%D8%AD%D9%92%D9%86%D9%8F-%D9%85%D9%8F%D8%AA%D8%B4%D8%A7%D8%A8%D9%90%D9%87%D9%88%D9%86-2016/work-sheets?grade=1')]</value>
      <webElementGuid>6b417d06-4e76-4726-9160-37f13cf2ce87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/a[3]</value>
      <webElementGuid>ab3d10ac-925f-4eb7-9c6c-666101a5728b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@type = 'button' and @id = 'radix-:rb:-trigger-work-sheets' and @href = '/e-school/lesson/%D9%86%D9%8E%D8%AD%D9%92%D9%86%D9%8F-%D9%85%D9%8F%D8%AA%D8%B4%D8%A7%D8%A8%D9%90%D9%87%D9%88%D9%86-2016/work-sheets?grade=1' and (text() = 'أوراق العمل' or . = 'أوراق العمل')]</value>
      <webElementGuid>1fc708e0-41da-4c3a-848d-746451c2f7ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
