<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>enter exam button</name>
   <tag></tag>
   <elementGuidId>97a13be4-396b-4f2e-baeb-3d97b91b8636</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[class*=&quot;styles_buttonVariantSolid__&quot;][class*=&quot;styles_buttonColorBlue__&quot;]&#xd;
</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;تسجيل الدخول&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4c37fcc9-69ab-4557-a4a9-a9ef282e327c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-max-w-full tw-w-full tw-transition tw-ease-in-out tw-duration-150 tw-font-bold tw-flex tw-items-center tw-justify-center tw-transition tw-ease-in-out tw-duration-150 styles_buttonVariantSolid__ljhsM styles_buttonColorBlue__0VHnR tw-rounded-[15px] tw-cursor-pointer tw-text-[16px] tw-py-[8px] tw-px-[16px]</value>
      <webElementGuid>5062ec25-33a0-4f6c-9f03-d259ffd262d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bdb89490-bb92-43d2-98c2-05ab7b64ecbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>تسجيل الدخول</value>
      <webElementGuid>e17596a5-b2f6-4c2e-84f5-4a4364c099ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r2q:&quot;)/div[@class=&quot;tw-flex tw-flex-col-reverse sm:tw-flex-row sm:tw-justify-end tw-flex tw-flex-col tw-flex-nowrap tw-justify-center tw-gap-[10px] sm:tw-flex sm:tw-flex-row sm:tw-flex-wrap sm:tw-flex-nowrap sm:tw-gap-[10px]&quot;]/div[@class=&quot;tw-w-full md:tw-m-auto md:tw-max-w-[250px]&quot;]/button[@class=&quot;tw-max-w-full tw-w-full tw-transition tw-ease-in-out tw-duration-150 tw-font-bold tw-flex tw-items-center tw-justify-center tw-transition tw-ease-in-out tw-duration-150 styles_buttonVariantSolid__ljhsM styles_buttonColorBlue__0VHnR tw-rounded-[15px] tw-cursor-pointer tw-text-[16px] tw-py-[8px] tw-px-[16px]&quot;]</value>
      <webElementGuid>ade69e2f-d566-499b-b109-574234a14e20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[7]</value>
      <webElementGuid>18d39d91-174d-4020-a4d6-03ceda1b23c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r2q:']/div[2]/div[2]/button</value>
      <webElementGuid>433fc7b3-9a86-493b-b526-9bea8ab12c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='انشاء حساب جديد'])[1]/following::button[1]</value>
      <webElementGuid>141a57b8-eab8-4d76-9fab-292e353f1afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='لطفاً! عليك تسجيل الدخول أولاً'])[1]/following::button[2]</value>
      <webElementGuid>7125e3c4-34fa-4dcc-af0c-929032547188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::button[1]</value>
      <webElementGuid>2f8d8d1b-155d-4096-8828-f295ed8a2a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='تسجيل الدخول']/parent::*</value>
      <webElementGuid>b203aef2-7c28-4599-b59c-d50cb3709063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>e2c66b4f-79e8-4456-8e12-720153a89d68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'تسجيل الدخول' or . = 'تسجيل الدخول')]</value>
      <webElementGuid>5d15b989-d867-499d-80a3-5ec31bea92e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
