<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>semester 1</name>
   <tag></tag>
   <elementGuidId>a1519c08-8390-4027-b7b7-54d0bce03476</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;radix-:rb:-trigger-semester-one&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;مدرستنا&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cc6527dc-254e-46b3-ad26-552e884bb3ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>مدرستنا</value>
      <webElementGuid>3ef338aa-9784-495e-9669-e0ad7a01415b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>كافة الشروحات للمواد | محتوى تعليمي مكتوب</value>
      <webElementGuid>7919d049-c1cf-41fc-a69e-9972c29661df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>medium tw-flex tw-items-center tw-justify-center tw-whitespace-nowrap tw-px-2 tw-text-[1vw] xl:tw-px-4 xl:tw-text-base tw-text-black hover:tw-bg-gray-100 tw-h-full</value>
      <webElementGuid>8072058e-577f-455a-91b5-283479bd583c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/e-school</value>
      <webElementGuid>9a289e94-d53a-43da-87dd-c46a538e1381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>مدرستنا</value>
      <webElementGuid>1cfa865b-16f9-487d-94cd-c33e03bd73d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar-card&quot;)/div[@class=&quot;tw-flex tw-h-full tw-items-center tw-justify-between tw-gap-4 tw-px-4 lg:tw-px-8&quot;]/div[@class=&quot;tw-hidden tw-h-full tw-items-center tw-justify-start lg:tw-flex&quot;]/div[@class=&quot;tw-hidden tw-h-full tw-items-center tw-justify-center lg:tw-flex&quot;]/a[@class=&quot;medium tw-flex tw-items-center tw-justify-center tw-whitespace-nowrap tw-px-2 tw-text-[1vw] xl:tw-px-4 xl:tw-text-base tw-text-black hover:tw-bg-gray-100 tw-h-full&quot;]</value>
      <webElementGuid>a87765df-3c7c-493b-8d2a-13f041f8271e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='navbar-card']/div/div[2]/div/a</value>
      <webElementGuid>441f2657-ff78-4866-aa78-36e15836f83c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'مدرستنا')]</value>
      <webElementGuid>bdfdc545-f742-432a-89e8-8d1436cd8867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='أخبارنا'])[1]/preceding::a[1]</value>
      <webElementGuid>c9918dd9-a6f4-403e-8f67-73d8a37df9b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الامتحانات الإلكترونية'])[1]/preceding::a[2]</value>
      <webElementGuid>4a3746ba-5a46-4cbe-a93a-9166ba42751c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='مدرستنا']/parent::*</value>
      <webElementGuid>01760987-c1eb-44c2-9b26-595d7f1bcdb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/e-school')]</value>
      <webElementGuid>ef2bbfcf-e896-4c89-98b7-5366a665ef39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>c9f99593-d36b-418f-a340-b7081179d714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'كافة الشروحات للمواد | محتوى تعليمي مكتوب' and @href = '/e-school' and (text() = 'مدرستنا' or . = 'مدرستنا')]</value>
      <webElementGuid>b2e0b257-65b2-47a1-9b07-a007e298da30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
