<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Free lesson card</name>
   <tag></tag>
   <elementGuidId>affca9db-5b83-4ff6-8d9b-ab43212152a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.bold.tw-line-clamp-2.tw-text-base.tw-text-start</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:R1qjml6:-content-free-lessons']/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;دروس مجانية&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3072bb46-e120-40e1-89ca-10bcbdb6d18c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center justify-center whitespace-nowrap rounded-sm px-3 py-1.5 text-sm font-medium ring-offset-background transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 data-[state=active]:bg-background data-[state=active]:text-foreground data-[state=active]:shadow-sm tw-h-[40px] max-md:!tw-text-[14px] max-md:tw-px-2 tw-whitespace-nowrap md:!tw-mt-8 max-md:tw-relative max-md:!tw-w-full max-md:tw-border-b-4 max-md:tw-rounded-none data-[state=active]:after:tw-absolute data-[state=active]:after:-tw-bottom-[11px] !tw-bg-[#6524BF] max-lg:!tw-w-full bold tw-text-white max-md:tw-border-none !tw-rounded-[14px] !tw-drop-shadow-xl tw-text-lg lg:tw-p-1 lg:tw-px-6 tw-flex tw-items-center tw-justify-center</value>
      <webElementGuid>a7de5a25-af74-46f1-b686-3aa0f7b5d6f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>be9a8b31-6c71-4357-9871-ece0a54b03cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>e23f6e7f-69b0-46b4-bdaf-5a3ce13e964c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e372f1c0-cb3e-4cbe-96ff-83f367a341d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:r1q:-content-free-lessons</value>
      <webElementGuid>ed43a12c-b065-4c35-8d08-80a767623895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>inactive</value>
      <webElementGuid>00efbba6-3215-402c-ad98-22eeb653826a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-:r1q:-trigger-free-lessons</value>
      <webElementGuid>b9bf0eb8-6a66-4da9-8c18-aff77f3138a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>77c85274-3c13-44e7-bc17-8a213de94913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orientation</name>
      <type>Main</type>
      <value>horizontal</value>
      <webElementGuid>6064d4c9-e0f6-4050-a184-20143dc72e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/e-school/%D8%A7%D9%84%D8%A3%D9%88%D9%84-%D9%81%D8%B5%D9%84-%D8%A3%D9%88%D9%84-%D8%B1%D9%8A%D8%A7%D8%B6%D9%8A%D8%A7%D8%AA/free-lessons?grade=1</value>
      <webElementGuid>a2f67517-2f31-4788-a1db-5a6f0dbecc63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>دروس مجانية</value>
      <webElementGuid>9aa0b6aa-4da4-4154-9da5-c0b324c3f074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r1q:-trigger-free-lessons&quot;)</value>
      <webElementGuid>59e947b0-98fd-476a-b58f-961d7de53ed6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='radix-:r1q:-trigger-free-lessons']</value>
      <webElementGuid>a66262ed-0644-4358-8484-ca0aab087dbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div[3]/div/a[4]</value>
      <webElementGuid>fcc68e80-c39b-48cb-9324-c203eaddec44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'دروس مجانية')]</value>
      <webElementGuid>d661849b-94df-48f3-9482-957c45504676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اختبارات المادة'])[1]/following::a[1]</value>
      <webElementGuid>9da2c481-f83e-478a-abb2-30baa2b6c4f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ملفات المادة'])[1]/following::a[2]</value>
      <webElementGuid>ebfa3cfe-05cd-4142-a496-184e3a0ce6a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='المرحلة التمهيدية: الأعداد حتى 10'])[1]/preceding::a[1]</value>
      <webElementGuid>342ca8b8-8dd7-4399-9944-afc406742957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الوحدة الأولى: الأعداد ضمن منزلتين'])[1]/preceding::a[1]</value>
      <webElementGuid>953e1429-6f75-4eeb-bedd-b6d6f76686d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='دروس مجانية']/parent::*</value>
      <webElementGuid>ff420069-622b-45ee-bf01-8b60bba9a977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/e-school/%D8%A7%D9%84%D8%A3%D9%88%D9%84-%D9%81%D8%B5%D9%84-%D8%A3%D9%88%D9%84-%D8%B1%D9%8A%D8%A7%D8%B6%D9%8A%D8%A7%D8%AA/free-lessons?grade=1')]</value>
      <webElementGuid>2ef5b1e6-b2d2-4706-b615-fdc69a9d5fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a[4]</value>
      <webElementGuid>25a492ca-7b06-4630-9d75-ea0491169dda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@type = 'button' and @id = 'radix-:r1q:-trigger-free-lessons' and @href = '/e-school/%D8%A7%D9%84%D8%A3%D9%88%D9%84-%D9%81%D8%B5%D9%84-%D8%A3%D9%88%D9%84-%D8%B1%D9%8A%D8%A7%D8%B6%D9%8A%D8%A7%D8%AA/free-lessons?grade=1' and (text() = 'دروس مجانية' or . = 'دروس مجانية')]</value>
      <webElementGuid>57d0a28c-28b1-486f-af9f-4a730b5837a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
