<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify by login</name>
   <tag></tag>
   <elementGuidId>0fcef4e5-aaa2-4966-aacb-3e0e3bb83865</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;radix-:r1p:&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;ابدأ الاختبار&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>da450391-a531-48cc-9b3e-50165f382889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-max-w-full tw-w-full tw-transition tw-ease-in-out tw-duration-150 tw-font-bold tw-flex tw-items-center tw-justify-center tw-transition tw-ease-in-out tw-duration-150 styles_buttonVariantSolid__ljhsM styles_buttonColorBlue__0VHnR tw-rounded-[10px] tw-cursor-pointer tw-text-[16px] tw-py-[8px] tw-px-[16px] !tw-text-white !tw-border-none !tw-bg-[#51C279]</value>
      <webElementGuid>45c6e96a-79d7-44e0-8ea1-7f599b56dfe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c57b108b-c292-43e8-8ff6-850cf50d5b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ابدأ الاختبار</value>
      <webElementGuid>8b353576-880c-4fdd-9a08-e3985c5ac399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r17:-content-quizzes&quot;)/div[@class=&quot;tw-flex tw-flex-wrap tw-justify-center 2xl:tw-justify-center tw-gap-6&quot;]/div[1]/div[@class=&quot;tw-rounded-lg tw-border tw-border-slate-200 tw-bg-white tw-text-slate-950 tw-shadow-sm dark:tw-border-slate-800 dark:tw-bg-slate-950 dark:tw-text-slate-50 tw-border-xl tw-grow tw-p-4 md:!tw-w-[312px] xsm:!tw-w-full tw-h-full tw-flex tw-flex-col tw-gap-4 tw-justify-between !tw-bg-[#F9F9F9]&quot;]/div[3]/button[@class=&quot;tw-max-w-full tw-w-full tw-transition tw-ease-in-out tw-duration-150 tw-font-bold tw-flex tw-items-center tw-justify-center tw-transition tw-ease-in-out tw-duration-150 styles_buttonVariantSolid__ljhsM styles_buttonColorBlue__0VHnR tw-rounded-[10px] tw-cursor-pointer tw-text-[16px] tw-py-[8px] tw-px-[16px] !tw-text-white !tw-border-none !tw-bg-[#51C279]&quot;]</value>
      <webElementGuid>4b85f746-f81c-4b4f-bbf0-1e752454bcdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>d85f6dcf-18ea-424e-b99f-31bba59ee000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r17:-content-quizzes']/div/div/div/div[3]/button</value>
      <webElementGuid>a7ef5343-395f-4c14-8957-196977c9c403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='التقويم الثاني علوم الصف الأول الفصل الأول'])[1]/preceding::button[1]</value>
      <webElementGuid>6263bb3b-c20f-4f53-9786-8a773dfb144f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/button</value>
      <webElementGuid>57205823-dfed-4b02-bc91-890f95ebbeb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'ابدأ الاختبار' or . = 'ابدأ الاختبار')]</value>
      <webElementGuid>f7ffe665-5f52-487f-8f9f-1f94db13c0d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
