<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>random semester</name>
   <tag></tag>
   <elementGuidId>22ea8bb1-e840-4cd8-9817-e177549025aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[2]/div/div/div/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;فصل أول&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7c37f68d-788a-45e3-b6ba-616fcb10b728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center justify-center whitespace-nowrap rounded-sm px-3 py-1.5 text-sm font-medium ring-offset-background transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 data-[state=active]:bg-background data-[state=active]:text-foreground data-[state=active]:shadow-sm tw-h-[48px] !tw-w-full tw-rounded-2xl tw-bg-[#6524BF] tw-text-white !tw-bg-gradient-to-b !tw-from-[#F2BF27] !tw-to-[#D17B0E] tw-flex tw-h-full tw-w-full tw-items-center tw-justify-center</value>
      <webElementGuid>d68eae1f-5710-4c9f-8c61-b4f326df783e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>51c8a14b-87a5-4627-bf1e-c6da45f2334f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>ecfe6580-9149-4651-b5d1-2a5985bc91a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d9f15248-c2d5-4768-9dd1-9f0bc2155e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:R1ajml6:-content-semester-one</value>
      <webElementGuid>69b35c40-1ba0-484b-9943-5e958e0be66e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>1e37c059-8bab-4260-8c96-facaa2ceb477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-:R1ajml6:-trigger-semester-one</value>
      <webElementGuid>a49ab26c-b2bf-4a54-b66b-0940462a1ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>bccbe20a-efc7-4ab2-a641-62ec862c27f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orientation</name>
      <type>Main</type>
      <value>horizontal</value>
      <webElementGuid>02427da0-2365-421f-8bc5-218af4a0c6b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/e-school/y/%D8%A7%D9%84%D8%A3%D9%88%D9%84/semester-one?grade=1</value>
      <webElementGuid>3a77ba36-cfce-442c-a419-238052d4483c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>فصل أول</value>
      <webElementGuid>4005e1db-71e5-4a2c-ad95-d0d13acb4299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:R1ajml6:-trigger-semester-one&quot;)</value>
      <webElementGuid>d3962ef6-aae9-47f9-b3b3-c65462ce7527</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='radix-:R1ajml6:-trigger-semester-one']</value>
      <webElementGuid>5558e978-6fa4-402e-aeee-1e6521802fc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/div/div/div[2]/div/a</value>
      <webElementGuid>76ca7130-28c0-4318-b21b-3115bdaa3226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'فصل أول')]</value>
      <webElementGuid>48965ff0-acec-4981-90d8-46546e2d91aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='هنا سوف تشاهد جميع موادك الدراسية'])[1]/following::a[1]</value>
      <webElementGuid>18dd9816-3987-48e3-b6af-730006936bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='هيا نتعلم مع جو اكاديمي'])[1]/following::a[1]</value>
      <webElementGuid>ab6b0647-2229-492b-bc2b-81e82d2db35a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='فصل ثاني'])[1]/preceding::a[1]</value>
      <webElementGuid>c3479ea8-709e-4265-bb6d-a9a87c58fd58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تذييل جو أكاديمي'])[1]/preceding::a[10]</value>
      <webElementGuid>1e1151b2-bd38-4dd8-86a5-81d061d3ed83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='فصل أول']/parent::*</value>
      <webElementGuid>18d71ed2-2f5a-4521-863b-672868cd3965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/e-school/y/%D8%A7%D9%84%D8%A3%D9%88%D9%84/semester-one?grade=1')]</value>
      <webElementGuid>3abd3ce3-b9e5-4b2d-99e0-1577112296d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/a</value>
      <webElementGuid>63baafd4-0e67-4fed-a0ac-afd7eb0f508b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@type = 'button' and @id = 'radix-:R1ajml6:-trigger-semester-one' and @href = '/e-school/y/%D8%A7%D9%84%D8%A3%D9%88%D9%84/semester-one?grade=1' and (text() = 'فصل أول' or . = 'فصل أول')]</value>
      <webElementGuid>9a26f55d-996a-4ff1-ab4e-96d9e0721b6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
