<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lessons</name>
   <tag></tag>
   <elementGuidId>334a4815-c738-4210-9a2b-48712d16fb74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:rc:']/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;1- الصخور النارية&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8b85c604-1a5f-4122-b233-10f0c070e695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-flex tw-items-center tw-justify-between tw-gap-6 tw-rounded-lg tw-bg-[#FFFFFF] tw-px-2 tw-py-4 tw-text-[#343434]</value>
      <webElementGuid>edf81722-771d-4a88-a117-a2cc883ed40a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/e-school/lesson/%D8%A7%D9%84%D8%B5%D8%AE%D9%88%D8%B1-%D8%A7%D9%84%D9%86%D8%A7%D8%B1%D9%8A%D8%A9-2083?grade=10</value>
      <webElementGuid>7ebc3b08-f887-4bef-9759-ac519f989897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1- الصخور النارية</value>
      <webElementGuid>15f0cf36-8b13-4a5f-aa95-d9e78bdb2a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:rc:&quot;)/div[@class=&quot;tw-pb-4 tw-pt-0 tw-flex tw-flex-col tw-gap-4 !tw-p-5 tw-mt-4 tw-bg-[#F9F9F9] !tw-mt-0 !tw-rounded-t-none !tw-rounded-b-[14px]&quot;]/a[@class=&quot;tw-flex tw-items-center tw-justify-between tw-gap-6 tw-rounded-lg tw-bg-[#FFFFFF] tw-px-2 tw-py-4 tw-text-[#343434]&quot;]</value>
      <webElementGuid>38dbb62b-7a93-455f-93a6-1dd956f71964</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:rc:']/div/a</value>
      <webElementGuid>48712c7e-7b4c-4931-bbae-6b3d581403fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الصخور'])[1]/following::a[1]</value>
      <webElementGuid>6e07e0bd-1546-44ea-872f-60d12ab6ecc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='دروس مجانية'])[1]/following::a[1]</value>
      <webElementGuid>98c8e5af-3d01-47e6-9536-e318dabde421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الصخور الرسوبية'])[1]/preceding::a[1]</value>
      <webElementGuid>f298a7d2-16f7-4a4c-9117-90cf04e02721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/e-school/lesson/%D8%A7%D9%84%D8%B5%D8%AE%D9%88%D8%B1-%D8%A7%D9%84%D9%86%D8%A7%D8%B1%D9%8A%D8%A9-2083?grade=10')]</value>
      <webElementGuid>7ce3a078-efde-4039-875e-644ae51381e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/a</value>
      <webElementGuid>32bc1793-8543-45db-a366-c5c6aa280dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/e-school/lesson/%D8%A7%D9%84%D8%B5%D8%AE%D9%88%D8%B1-%D8%A7%D9%84%D9%86%D8%A7%D8%B1%D9%8A%D8%A9-2083?grade=10' and (text() = '1- الصخور النارية' or . = '1- الصخور النارية')]</value>
      <webElementGuid>d96daff5-88fa-49c8-aea0-5b906482f736</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
