<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lessons</name>
   <tag></tag>
   <elementGuidId>334a4815-c738-4210-9a2b-48712d16fb74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:rc:']/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div a.tw-flex.tw-gap-6.tw-items-center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;1- الصخور النارية&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>023d0744-79c8-4f4f-936a-4e3ffb11379b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-flex tw-items-center tw-justify-between tw-gap-6 tw-rounded-lg tw-bg-[#FFFFFF] tw-px-2 tw-py-4 tw-text-[#343434]</value>
      <webElementGuid>3f3d901f-dc45-4036-904d-e5ccb40efad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/e-school/lesson/%D8%A7%D9%84%D8%B5%D8%AE%D9%88%D8%B1-%D8%A7%D9%84%D9%86%D8%A7%D8%B1%D9%8A%D8%A9-2083?grade=10</value>
      <webElementGuid>f8efc358-c6aa-44c3-b8a5-c313dd2dbf0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1- الصخور النارية</value>
      <webElementGuid>3241b6c8-eedf-49c5-b1f3-6a3d4d247265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:rc:&quot;)/div[@class=&quot;tw-pb-4 tw-pt-0 tw-flex tw-flex-col tw-gap-4 !tw-p-5 tw-mt-4 tw-bg-[#F9F9F9] !tw-mt-0 !tw-rounded-t-none !tw-rounded-b-[14px]&quot;]/a[@class=&quot;tw-flex tw-items-center tw-justify-between tw-gap-6 tw-rounded-lg tw-bg-[#FFFFFF] tw-px-2 tw-py-4 tw-text-[#343434]&quot;]</value>
      <webElementGuid>c44038ed-e0f9-4f64-af47-389059ecc68c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:rc:']/div/a</value>
      <webElementGuid>70ee6f47-4302-42c5-9e38-1e33044c7fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الصخور'])[1]/following::a[1]</value>
      <webElementGuid>6b624422-9e60-40d9-9a46-22f67d67bbc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='دروس مجانية'])[1]/following::a[1]</value>
      <webElementGuid>8cd1325c-b1c5-4350-b8d6-4e59e2606875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الصخور الرسوبية'])[1]/preceding::a[1]</value>
      <webElementGuid>566dcace-df61-48e0-9665-d5d405501f0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/e-school/lesson/%D8%A7%D9%84%D8%B5%D8%AE%D9%88%D8%B1-%D8%A7%D9%84%D9%86%D8%A7%D8%B1%D9%8A%D8%A9-2083?grade=10')]</value>
      <webElementGuid>f4caf6e4-86a2-4e6f-84c5-4c17a473d704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/a</value>
      <webElementGuid>cbd9da55-994f-4827-b890-6f0b8e424616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/e-school/lesson/%D8%A7%D9%84%D8%B5%D8%AE%D9%88%D8%B1-%D8%A7%D9%84%D9%86%D8%A7%D8%B1%D9%8A%D8%A9-2083?grade=10' and (text() = '1- الصخور النارية' or . = '1- الصخور النارية')]</value>
      <webElementGuid>b023aafe-bf21-414d-acbb-839936a82728</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
