<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify uint</name>
   <tag></tag>
   <elementGuidId>0e4038c1-5593-438b-a535-293b0f2b7684</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:R1qjnl6:-content-book-content']/div/div/h3/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[data-orientation='vertical'][data-radix-collection-item=''][type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;الصخور&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>818b708e-7870-44a3-8f5c-d509fd475b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e083a592-aebe-4eef-8287-f9c69022e6b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:rc:</value>
      <webElementGuid>af7be380-1e05-474a-a13f-5ed37154e40a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>956d5686-fdbf-4cf1-809c-468b42562de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>33fe4340-8739-4164-8d5a-ca26a1e630de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orientation</name>
      <type>Main</type>
      <value>vertical</value>
      <webElementGuid>8dcd6957-e895-46b4-b108-cba354730fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-:rb:</value>
      <webElementGuid>e58018ae-2253-4975-9a13-6170273817e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-flex tw-flex-1 tw-items-center tw-justify-between tw-py-4 tw-font-medium tw-transition-all hover:tw-underline [&amp;[data-state=open]>svg]:tw-rotate-180 bold tw-text-lg tw-p-3 tw-w-full tw-bg-[#F9F9F9] tw-rounded-[14px] data-[state=open]:tw-rounded-b-none tw-text-[#1A428A]</value>
      <webElementGuid>cf32596e-22ec-49fc-bddd-31572f9aacdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>الصخور</value>
      <webElementGuid>33cf0fb1-ed20-4587-8f80-602351fec382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:rb:&quot;)</value>
      <webElementGuid>f0109312-672b-448f-a00b-96843cf48b77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='radix-:rb:']</value>
      <webElementGuid>dfbad097-81e4-4c2d-a36a-33e96267a016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:R1qjnl6:-content-book-content']/div/div/h3/button</value>
      <webElementGuid>bad2a936-ee7e-4051-9b27-b247cb0057aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='دروس مجانية'])[1]/following::button[1]</value>
      <webElementGuid>7050e6c5-93d5-4218-ba07-6fef9d1ebd53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اختبارات المادة'])[1]/following::button[1]</value>
      <webElementGuid>da3d52ab-3233-4800-b082-4b0d5e99026c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='النجوم'])[1]/preceding::button[1]</value>
      <webElementGuid>38c7ca2d-3d46-470a-b16f-6550284f4dce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تذييل جو أكاديمي'])[1]/preceding::button[2]</value>
      <webElementGuid>fa268244-9aaf-4f21-a107-36d7ec2b6386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='الصخور']/parent::*</value>
      <webElementGuid>5ac9bdf5-291c-4fda-9512-bae58bf594df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/button</value>
      <webElementGuid>6c38a20a-ca29-43ad-a4fe-caae6c9c1137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'radix-:rb:' and (text() = 'الصخور' or . = 'الصخور')]</value>
      <webElementGuid>de53c4e0-9e63-4ee5-af88-5e59d1e2372f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
