<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>E-school</name>
   <tag></tag>
   <elementGuidId>6b710dd6-5926-491d-ac90-0aad075e5f94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'مدرستنا')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;مدرستنا&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3ad1bee2-803b-4927-8446-ccd28362b484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>مدرستنا</value>
      <webElementGuid>85992942-6368-45c1-8832-598da909c1fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>كافة الشروحات للمواد | محتوى تعليمي مكتوب</value>
      <webElementGuid>3743c2ec-2ed4-4f59-945d-d716d2d5f612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>medium tw-flex tw-items-center tw-justify-center tw-whitespace-nowrap tw-px-2 tw-text-[1vw] xl:tw-px-4 xl:tw-text-base tw-border-b-2 tw-border-brand-blue tw-bg-brand-blue/5 tw-text-brand-blue tw-h-full</value>
      <webElementGuid>5c89ef45-6463-45e6-bb8f-45341db4da6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/e-school</value>
      <webElementGuid>6455900e-d875-44f4-a91c-4927901c5994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>مدرستنا</value>
      <webElementGuid>70d02b99-b5c1-4d08-9218-1ba3016efb2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar-card&quot;)/div[@class=&quot;tw-flex tw-h-full tw-items-center tw-justify-between tw-gap-4 tw-px-4 lg:tw-px-8&quot;]/div[@class=&quot;tw-hidden tw-h-full tw-items-center tw-justify-start lg:tw-flex&quot;]/div[@class=&quot;tw-hidden tw-h-full tw-items-center tw-justify-center lg:tw-flex&quot;]/a[@class=&quot;medium tw-flex tw-items-center tw-justify-center tw-whitespace-nowrap tw-px-2 tw-text-[1vw] xl:tw-px-4 xl:tw-text-base tw-border-b-2 tw-border-brand-blue tw-bg-brand-blue/5 tw-text-brand-blue tw-h-full&quot;]</value>
      <webElementGuid>6169f556-bd37-45ca-8a9b-c68e7e02379a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='navbar-card']/div/div[2]/div/a</value>
      <webElementGuid>a9437f93-997b-4fc0-a087-5b93c0d59ed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'مدرستنا')]</value>
      <webElementGuid>8aea6fce-a3f4-453c-9c8f-d493424f756b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='أخبارنا'])[1]/preceding::a[1]</value>
      <webElementGuid>b4630b33-95d1-43e9-a393-767b02487b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الامتحانات الإلكترونية'])[1]/preceding::a[2]</value>
      <webElementGuid>20af48c3-3fa8-477e-a0fa-f15ec9a294ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='مدرستنا']/parent::*</value>
      <webElementGuid>305ba882-52c6-4d21-a313-3f639a861bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/e-school')]</value>
      <webElementGuid>e2d0b15f-c33c-4738-9a95-e5c7b504638e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>dd22582b-1d13-43f9-a280-b72b11bfbb1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'كافة الشروحات للمواد | محتوى تعليمي مكتوب' and @href = '/e-school' and (text() = 'مدرستنا' or . = 'مدرستنا')]</value>
      <webElementGuid>80b573ce-9872-4f76-b0dd-5d3c6aab7b67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
