<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>E-school</name>
   <tag></tag>
   <elementGuidId>6b710dd6-5926-491d-ac90-0aad075e5f94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div a.medium.xl:tw-px-4[aria-label='مدرستنا']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'مدرستنا')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;مدرستنا&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cc5b0a57-10b7-4be6-89a3-25d8a1fb22b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>مدرستنا</value>
      <webElementGuid>503586e2-c5ea-4aae-81d8-51e0dbd30738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>كافة الشروحات للمواد | محتوى تعليمي مكتوب</value>
      <webElementGuid>2ab031f6-3dff-43c2-9a5a-5d6db3cbba5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>medium tw-flex tw-items-center tw-justify-center tw-whitespace-nowrap tw-px-2 tw-text-[1vw] xl:tw-px-4 xl:tw-text-base tw-border-b-2 tw-border-brand-blue tw-bg-brand-blue/5 tw-text-brand-blue tw-h-full</value>
      <webElementGuid>1afd2c46-2fb1-4fd5-9472-87b058ad63a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/e-school</value>
      <webElementGuid>5a233809-1bf3-429b-9680-73dfa48ba164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>مدرستنا</value>
      <webElementGuid>7059a6e9-e7b4-4f78-a456-ecaaec7fb816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar-card&quot;)/div[@class=&quot;tw-flex tw-h-full tw-items-center tw-justify-between tw-gap-4 tw-px-4 lg:tw-px-8&quot;]/div[@class=&quot;tw-hidden tw-h-full tw-items-center tw-justify-start lg:tw-flex&quot;]/div[@class=&quot;tw-hidden tw-h-full tw-items-center tw-justify-center lg:tw-flex&quot;]/a[@class=&quot;medium tw-flex tw-items-center tw-justify-center tw-whitespace-nowrap tw-px-2 tw-text-[1vw] xl:tw-px-4 xl:tw-text-base tw-border-b-2 tw-border-brand-blue tw-bg-brand-blue/5 tw-text-brand-blue tw-h-full&quot;]</value>
      <webElementGuid>f42b1c8c-22bb-406b-8251-252abc8b353b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='navbar-card']/div/div[2]/div/a</value>
      <webElementGuid>7f7da165-6ed6-46cd-a12c-f25e8c005b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'مدرستنا')]</value>
      <webElementGuid>ce2ca6c3-a5d0-404f-a47d-484bb34dabb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='أخبارنا'])[1]/preceding::a[1]</value>
      <webElementGuid>63da8f3f-44c5-43a2-9b46-55f63cbeea60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الامتحانات الإلكترونية'])[1]/preceding::a[2]</value>
      <webElementGuid>c62df4e4-114f-4fb1-b573-186233e30e18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='مدرستنا']/parent::*</value>
      <webElementGuid>4369e849-b95b-43c4-b45f-adeebd9fb0dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/e-school')]</value>
      <webElementGuid>d185831c-e5d9-43ea-b195-7f6c45394749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>a6e79024-9c0b-4188-8b03-cd8953647b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'كافة الشروحات للمواد | محتوى تعليمي مكتوب' and @href = '/e-school' and (text() = 'مدرستنا' or . = 'مدرستنا')]</value>
      <webElementGuid>bbf3ae06-f296-4f97-a696-2368c06e99fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
