<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>material button</name>
   <tag></tag>
   <elementGuidId>88a4f8f3-3913-4ca0-bac8-e42c656f045c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:r1l:-content-semester-one']/div/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Subject Image العلوم (ف1)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>472d7787-45a4-4572-ade1-c7c374e7891f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-rounded-lg tw-border tw-border-slate-200 tw-bg-white tw-text-slate-950 tw-shadow-sm dark:tw-border-slate-800 dark:tw-bg-slate-950 dark:tw-text-slate-50 !tw-h-[190px] !tw-w-full !tw-rounded-[14px] tw-p-6 hover:tw-scale-105</value>
      <webElementGuid>28207674-4e0d-4943-9631-2f384f39f5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>العلوم(ف1)</value>
      <webElementGuid>c2ac0934-83a0-4fb3-bf30-47e30d219b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r1l:-content-semester-one&quot;)/div[@class=&quot;tw-mt-6 tw-grid tw-grid-cols-1 tw-gap-x-5 tw-gap-y-8 xsm:tw-grid-cols-2 xsm:tw-justify-center sm:tw-grid-cols-2 md:tw-grid-cols-3 lg:tw-grid-cols-4 xl:tw-grid-cols-5 2xl:tw-justify-start 2xl:tw-gap-x-5&quot;]/a[1]/div[@class=&quot;tw-rounded-lg tw-border tw-border-slate-200 tw-bg-white tw-text-slate-950 tw-shadow-sm dark:tw-border-slate-800 dark:tw-bg-slate-950 dark:tw-text-slate-50 !tw-h-[190px] !tw-w-full !tw-rounded-[14px] tw-p-6 hover:tw-scale-105&quot;]</value>
      <webElementGuid>303ac3fe-e3d4-4865-93cb-fa00d41050b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r1l:-content-semester-one']/div/a/div</value>
      <webElementGuid>e86f7ca0-99f5-410a-99cb-fc232f5033c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='فصل ثاني'])[1]/following::div[3]</value>
      <webElementGuid>fd56091d-6fe5-42ef-a1e7-60f0a5fd4ab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='فصل أول'])[1]/following::div[3]</value>
      <webElementGuid>f3b6967e-ba8e-4417-b92a-9026da6a10d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تذييل جو أكاديمي'])[1]/preceding::div[25]</value>
      <webElementGuid>193aa3e1-fe35-487a-b657-623a7f04fc83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='روابط سريعة'])[1]/preceding::div[26]</value>
      <webElementGuid>3309e841-a3e7-498a-bca4-553da1e6038e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>d9fa76e6-5b0f-4cf8-848e-43efc79e30f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'العلوم(ف1)' or . = 'العلوم(ف1)')]</value>
      <webElementGuid>663dbcc9-d01e-4c3e-9c38-01fe0768ccde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
